### ISSUE TITLE
[BUG] Remove teams in pugs mode causes some problems

### ISSUE THREAD

**Issue by thboss** [PhlexPlexico/G5API#108]
**Describe the bug**
Teams removed from the `team` table on the match end if `is_pug =1`, so that sets all related columns to `null`

**To Reproduce**
http://g5.thboss.xyz:3301/playerstats/match/1 and here http://g5.thboss.xyz:3301/matches/1
you can see `team_id` set to `null` for all players
For example, in the Discord bot, I added a command to display the match scoreboard, and it works fine when the match is live
![Screenshot 2021-07-10 035015](https://user-images.githubusercontent.com/40491968/125147282-ea45f600-e132-11eb-87d9-8b6f8610995f.png)
But on the match end and teams removed from `team` table, this function doesn't work because all players' `team_id` set to `null`

**Expected behavior**
I think teams shouldn't delete even if `is_pug` is enabled or should be a separated table for the pug teams.

**Desktop**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [90]

**Server info
 - Ubuntu 20.04
 - NodeJS version 14

**Comment by PhlexPlexico** [comment]
The reasons why teams are deleted is a long contested discussion I've had with another developer. The reason behind it right now is because we want to control a way to have PUGs, without having a bunch of teams created. If you've noticed, the team IDs are up in the couple hundreds right now, and it would be ridiculous to have those teams stored since they're rather temporary. The match data can still be output, as per seen in the actual link to G5V, you just need to get the data from the map_stats and player_stats table is all and not rely on the team id I believe.

**Comment by thboss** [comment]
I notice in your web api for example this match's player_stats https://phlex.avidgamers.me/api/playerstats/match/391
team ids are NOT set to null even after teams remove from the team table!! you can see team id 653 is not exist https://phlex.avidgamers.me/api/teams/653

but in my web api, team ids are set to null (in playerstats), and no way to know the player's team (team1 or team2).

**Comment by PhlexPlexico** [comment]
Hmmm... Well that shouldn't be the case. I know after the out finishes it deletes the team, but the `team_id` (and name of the team!) Exist on the match itself, which you can link to the player stats. Depending on if you cancel a match or delete a match it may have undefined behaviour. But yeah, teams are deleted to avoid filling up the tables for teams, that's working as intended. I'm currently using the master branch right now and it seems to be working as intended.

**Comment by PhlexPlexico** [comment]
So I looked into it, and I believe there may be an error on my end. You're right in that the deletes shouldn't cascade off into that table I think. I'll think about this and replace a small database patch for it!

**Comment by PhlexPlexico** [comment]
So I think the main way to approach this is to remove the foreign key constraint on the `match`, which would essentially fix this problem, but also I have some issues with database integrity. 

Another approach would be to not delete the team data from the team table, but include a new boolean column that signals `deleted` and make it an index, which would (hopefully) make lookups fast as the database grows and only show the teams who are not deleted. That would require rewriting a lot of queries on the `team` table though, but I think that may be the better approach.

**Comment by thboss** [comment]
I also prefer the second choice since more tables reference the team id (`match`, `map_stats`, `player_stats`) and maybe remove the foreign key constraint breaks some functionality.

**Comment by PhlexPlexico** [comment]
Hey @thboss please checkout the branch `refactor-db-calls`, this branch should now allow the team names to be stored in the `player_stats` table, which will allow us to sort match tables without breaking any constraints, and other calls were updated as needed (such as cancelling/forfeiting matches). I don't believe this should cause any issues and you should get the data needed from now on :)
