### ISSUE TITLE
[Feature Request] Change API Authentication To Use Headers

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#116]
### Discussed in https://github.com/PhlexPlexico/G5API/discussions/113

<div type='discussions-op-text'>

<sup>Originally posted by **kdev** August 17, 2021</sup>
Let's say I have a Service that tries to fetch some data or post to a restricted endpoint: How would I authenticate myself? It does not seem to be done with headers, so how is it done? </div>

See #115

**Comment by PhlexPlexico** [comment]
I suppose it doesn't like that change with the safe navigation. Would you be able to back out that change by any chance?

**Comment by kdev** [comment]
Do you still want this to be done? Because you closed your PR

**Comment by PhlexPlexico** [comment]
If you wouldn't mind. I may not have the time today to look into it :) but from what I can see is that optional chaining is not really supported by Jest/Node quite yet (the version that this project requires, at least), so I think that may be the issue. So long as you can update the ES setting, or just find another way of fixing it, that would be amazing!

Thanks!

**Comment by PhlexPlexico** [comment]
Also, if all tests pass using Node 14 (which I believe is where ES2020 is supported), I wouldn't be opposed to setting the lowest required version to 14 :)

**Comment by kdev** [comment]
Will do ^^
