### ISSUE TITLE
[BUG] Almost any server error causes G5API to crash

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#123]
**Describe the bug**
Almost any server error causes G5API to crash

**To Reproduce**
1. e.g. use sv_lan 1 on LAN servers.
2. That causes get5 to be unable to check steamids
3. That crashes G5API

**Expected behavior**
At least an option to restart G5API automatically on failure and recover missing data (change in webapi plugin to retry all API calls when not successful)

**Server info
 - OS: Debian
 - Version: 11
 - NodeJS version:  v16.10.0

**Comment by PhlexPlexico** [comment]
Do you have the error logs from G5API to support this? Last I checked, all server calls are fairly safe and shouldn't cause a crash, just an error.

**Comment by kubo6472** [comment]
Where to grab the ones from G5API exactly, please?

**Comment by PhlexPlexico** [comment]
The logs would be located in `~/.pm2/logs` I believe, and it would be `G5API-error.log`

**Comment by kubo6472** [comment]
https://hastebin.com/codusucuro.properties Full error log

**Comment by PhlexPlexico** [comment]
Wow that is a myriad of problems that have previously been encountered.

What version of redis are you running? Did you install all your npm packages? It looks like it cannot find redis.
Second, the unexpected output from JSON means that get5 isn't installed on your server, or `get5_web_available` is returning undefined behaviour.
Third is a database issue that has been outstanding for the past while. I have no idea how dead connections are ending up in the connection pool. I've ran into this problem several times, and the only solution so far is to restart the API once in awhile and bump up your connection pool to a ridiculous amount.
Eaddrnotfound means that your network isn't resolving DNS queries as well, which means there could be an issue with your outbound connections on your API server.

**Comment by kubo6472** [comment]
Whoah, that is quite a lot of errors :D

**Comment by PhlexPlexico** [comment]
Yeah, so the one that would be outstanding would be the database connection errors, which I have no idea how to fix. But this just looks like someone didn't run the initial setup for the npm packages with `yarn`, and do their setups with their configs. That should fix most issues :)

**Comment by kubo6472** [comment]
So, after then resolving most of the issues: I fixed redis, and it was up during the whole period of operation. MariaDB needed to stay accessible, since there were other services using just that, and running just fine. And yep, all the packages were installed using yarn on the NodeJS version: v16.10.0

**Comment by PhlexPlexico** [comment]
So are you still running into crashes then? What is the game server replying with `get5_web_available`?

**Comment by kubo6472** [comment]
I was pulling the latest master from git and moving it over to its final folder. Otherwise everything stayed as is. Checked out the guide a few more times when the errors where happening during testing. As I noticed, redis had problems, so I cleaned-installed it and when I verified everything was okay, we started the matches. The crashes of get5 api were happening, when there was the gameserver error.

**Comment by kubo6472** [comment]
```
get5_web_available
{
"gamestate": 0,
"available": 1,
"plugin_version": "0.7.2"
}
```

**Comment by PhlexPlexico** [comment]
Have you tried using the latest release of G5API instead of just what is on the master branch? I just merged in some additional stat tracking the other day, which may be causing some issues.

**Comment by kubo6472** [comment]
I needed to stay on edge bcs of the BO2 fixes and other FRs merged since. But I can try now.

**Comment by PhlexPlexico** [comment]
Hmm, well do you have some more logs with those errors pruned out? Are you using G5WS? If so, do you have Rest in PAWN on your server, and sm-json?

**Comment by kubo6472** [comment]
Compiled your G5WS with RIP installed, but https://github.com/thraaawn/SMJansson this is missing from all servers. No errors during startup anywhere.

**Comment by PhlexPlexico** [comment]
Well there should be a release for it, but just `sm-json`, `SteamWorks Extension` and `Rest in PAWN Extension` are all required, and if G5WS is reporting back that's fine. But that being said, I would definitely check your firewall setup because that entire error list looks like it just can't even get anything from outside the network. I.e. that server can't even ping `google.com` let alone any IPs as well since it's just refusing connections.

**Comment by kubo6472** [comment]
May this be correct then? https://github.com/clugg/sm-json/releases/tag/v3.2.1

**Comment by PhlexPlexico** [comment]
I believe so, but as I said, the majority of the errors prior to this was not being able to access anything outside your network. This is most likely a firewall issue?

**Comment by kubo6472** [comment]
> I believe so, but as I said, the majority of the errors prior to this was not being able to access anything outside your network. This is most likely a firewall issue?

I ran this on a LAN with very limited internet access. The ports were being opened one by one as I was on call with an ISP Worker, who did networking in there. It worked out in the end. But the G5API gived up the ghosts at least a dozen times that night. Nvm. Need to do some cleanup in the database, as those matches are not finished. Will be downgrading to both the release of G5API and the server plugin. I am going by your requirements which list RIP, and then Sean's with Steamworks. No mention of any sm-json or smjannson ext. anywhere.

**Comment by PhlexPlexico** [comment]
It's usually there for compiling, unsure if it's actually needed. But that would also be the reason, is the fact you had limited access. As for cancelling matches (if the servers are offline) you can simply go cancel the matches and delete all cancelled matches from the "MY Matches" tab on G5V. So yeah, seems like it was a connection issue, not much with the API, it can't work unless there's connections :)

**Comment by kubo6472** [comment]
> It's usually there for compiling, unsure if it's actually needed. But that would also be the reason, is the fact you had limited access. As for cancelling matches (if the servers are offline) you can simply go cancel the matches and delete all cancelled matches from the "MY Matches" tab on G5V. So yeah, seems like it was a connection issue, not much with the API, it can't work unless there's connections :)

I just installed the release version of G5API and the G5WS plugin. Don't have the circumstances to exactly replicate this as well. I cleared the pm2 logs. I'd appreciate if you could keep this open as I will try and add more info down the line.

**Comment by PhlexPlexico** [comment]
I'll keep it open for a week or two just in case, but it does sound like you have it resolved :)

**Comment by PhlexPlexico** [comment]
Going to close this off now since there hasn't been any more reported issues, and I believe it was not related to this project.
