### ISSUE TITLE
[BUG] BO2's not ending

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#128]
The downgrade idea fixed the crashing, but broke bo2 ending. I am sure the finish event got called, but the match is still running in the panel. can I end it "manually"?

**Comment by PhlexPlexico** [comment]
Please make sure you use the templates provided for describing the bug. I assume this is in relation to #98? Absolutely nothing has changed in regards to the application where it would call a crash, nor fail on Bo2. That is sounding more like an error on Get5, more than the API.

As for the API crashing - did you update the database as well? There are some new tables and new columns in the player_stats tables.

Once again, logs would be more than helpful to see this problem you're experiencing. Without logs, I can't determine where the fail point is.

**Comment by PhlexPlexico** [comment]
I mean, they would just be in the container for the API. They won't be in the G5V Docker container, since I assume that's where you're looking since you're referencing the Light file which is only located in G5V.

Thanks!

**Comment by PhlexPlexico** [comment]
Hahaha, I think I may have found a possible issue with this. I'll just need to double check some SourcePawn operators. This may be the offending issue here - 
https://github.com/PhlexPlexico/G5WS/blob/45ba9d8e7b56145d07f7000dcaeef4f22a38c8b2/scripting/G5WS.sp#L474-L480

It appears that if a match winner is none, which means that the match won't be sent to to the server. This can be easily changed I think to check if matches were played or if its a BO2 scenario... Would you mind testing a plugin for me? :)

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/G5WS/releases/download/V3.0.1/G5WS.zip this should fix the issue that you're having (I hope)!

**Comment by kubo6472** [comment]
I will upload it asap, I'm on my way to school so ETA 8-10 hours till I can let you know.

**Comment by kubo6472** [comment]
As for the DB update, I can just run the migrate cmd again, right? The logs folder is still nowhere to be found...

**Comment by kubo6472** [comment]
> and will be located in `~/.pm2/logs` in the G5API container.

I am so sorry, but I am completely unable to find it
![image](https://user-images.githubusercontent.com/26146502/137520134-1c8d9421-a394-42de-a4e0-6d4f6b146628.png)
Just found a node_modules folder with that name that is just the package ifself. there was paths.js from which I got this part. 
![image](https://user-images.githubusercontent.com/26146502/137520490-4a01a149-ef41-48c3-b2c0-81ad8fc642fd.png)
so I tried every path with no luck. dunno where else it could be then.

**Comment by kubo6472** [comment]
Whoah, totally forgot about the API update. Thanks. Gotta do that too.

**Comment by kubo6472** [comment]
get5.veto_side won't be created in the migration for some reason, so I am creating it manually

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/137621049-8af4af44-99bc-4f78-ac8f-1f8ebb36ddbd.png)
vetos are empty, dunno if that is related to what we have just done, cuz they worked b4.

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/137621073-c52b96fa-a177-44f9-bd0b-954d7ac9c093.png)
but match finished succesfully. so big thanks and moving that to a new issue
