### ISSUE TITLE
[BUG] Some more docker errors

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#136]
**Describe the bug**
package.json is not where it is supposed to be

**To Reproduce**
1. Build and run in Docker

**Expected behavior**
It would just run

**Screenshots**
![image](https://user-images.githubusercontent.com/26146502/140887385-815673e1-8109-493c-8928-4fec4503c200.png)

**Server info
 - OS: Host: Alpine
 - Version: 3.14
 - NodeJS version: 14.17.5

**Additional context**
I think we are not cd-ing to the correct directory. Where exactly the problem lies is just as much a mystery to me, as to anyone.

**Comment by kubo6472** [comment]
The production.json is not reading the env vars still :/

**Comment by kubo6472** [comment]
The pm2 was never initialized for some reason

**Comment by PhlexPlexico** [comment]
There is no need to do a cd anywhere since the `setEnv` runs on full, complete paths. PM2 won't be able to launch without the production.json values in place. Did you include the new environment variable `-e UPLOADDEMOS="" \` and set that to true or false? That is now required.

**Comment by kubo6472** [comment]
Yes, I've set that up

**Comment by PhlexPlexico** [comment]
I'm unable to replicate this. I've just setup a brand new instance of docker on WSL2, ran docker container for mariadb with port 3306 visible, and then ran `docker build -t phlexplexico\g5api:latest .`. After that I ran what was in the readme with the proper values, and it is running and installing just fine. The only issue I had was setting up the database and ensuring I was using the right docker network IP.

**Comment by kubo6472** [comment]
WHAT?! It works perfectly now. I must've messed something up. Thanks sm. I am getting my two containers ready to be released into the wild. Possibly later even built automatically with ghcr, as I mentioned. But right now, I am still completely newbie in that regard. Closing this.

**Comment by PhlexPlexico** [comment]
No worries, if there's any issues or questions, feel free to leave something in the Discussion/Q&A as well :)

**Comment by kubo6472** [comment]
Well, I think I made it work:
https://hub.docker.com/r/kubo6472/g5v
https://hub.docker.com/r/kubo6472/g5api
It should be documented good enough. For now the update process is 
hands-on ah, but I plan on doing some light automation now that this 
works :D
