### ISSUE TITLE
[BUG] Failure Finding Production Environment

### ISSUE THREAD

**Issue by Shaneajm** [PhlexPlexico/G5API#143]
**Describe the bug**
Apologies if I'm just missing something simple but when I'm trying to create the production database I run into an issue where the environment isn't found.

**To Reproduce**
1. Install dependencies with yarn
2. Fill out the `production.json` file. (I have tried with in `/config/development/test/` and in `/config` - same issue with both)
3. Run `yarn migrate-create-prod`

**Expected behavior**
Database should be migrated.

**Output**
```
shane@G5-API:~/G5-API$ yarn migrate-create-prod
yarn run v1.22.17
$ MYSQL_FLAGS="-CONNECT_WITH_DB" db-migrate --env production --config /config/production.json db:create get5
[ERROR] Error: Could not find database config file '/config/production.json'
    at Object.exports.loadFile (/home/shane/G5-API/node_modules/db-migrate/lib/config.js:48:13)
    at loadConfig (/home/shane/G5-API/node_modules/db-migrate/lib/commands/helper/load-config.js:12:18)
    at new dbmigrate (/home/shane/G5-API/node_modules/db-migrate/api.js:77:43)
    at Object.module.exports.getInstance (/home/shane/G5-API/node_modules/db-migrate/index.js:85:10)
    at /home/shane/G5-API/node_modules/db-migrate/bin/db-migrate:32:25
    at /home/shane/G5-API/node_modules/resolve/lib/async.js:133:25
    at maybeRealpath (/home/shane/G5-API/node_modules/resolve/lib/async.js:41:9)
    at /home/shane/G5-API/node_modules/resolve/lib/async.js:129:24
    at ondir (/home/shane/G5-API/node_modules/resolve/lib/async.js:309:27)
    at onex (/home/shane/G5-API/node_modules/resolve/lib/async.js:201:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Server info**
 - OS: Ubuntu
 - Version: 20.04
 - NodeJS version: v16.13.0 (yarn 1.22.17)

**Additional context**
I've tried doing `export NODE_ENV=production` and then running the command but I run into the same issue.

**Comment by PhlexPlexico** [comment]
So within the project you should have the `confif` folder and there are a handful of files in there when you clone the repository. You can just rename the `production.json.template` to `production.json` and fill in the values there. The config just stays in that folder. Would you mind screenshottong the contents of that folder? According to the logs it should be in `/home/shane/G5-API/config`

**Comment by Shaneajm** [comment]
I'm dumb. Inside the `production.json` template I hadn't changed the value to production 😅 It works now.
```
"uploadDemos": false
  },
  "production": {
    "driver": "mysql",
    ```

**Comment by PhlexPlexico** [comment]
Yeah if you just copy/paste the production template you shouldn't have to worry, but glad you figured it out 😄
