### ISSUE TITLE
Invalid Key Size

### ISSUE THREAD

**Issue by Shaneajm** [PhlexPlexico/G5API#144]
Heyo! Back again 😅

I have the API and reverse proxy with NGINX set up but I'm running into an issue where after logging in with Steam, the session doesn't get stored. 

```
GET /auth/steam 302 76.828 ms - 0
::ffff:127.0.0.1 - - [21/Nov/2021:05:28:27 +0000] "GET /auth/steam HTTP/1.1" 302 0 "mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
Error: invalid key size (must be 16, 24 or 32 bytes)
    at AES._prepare (/home/shane/G5-API/node_modules/aes-js/index.js:206:19)
    at new AES (/home/shane/G5-API/node_modules/aes-js/index.js:198:14)
    at new ModeOfOperationOFB (/home/shane/G5-API/node_modules/aes-js/index.js:589:21)
    at Function.encrypt (/home/shane/G5-API/utility/utils.js:116:20)
    at /home/shane/G5-API/utility/auth.js:79:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERRORERRORERRORERRORERRORERRORERRORERROR Error: invalid key size (must be 16, 24 or 32 bytes)ERRORERRORERRORERRORERRORERRORERRORERROR
```
**Server info**

**OS:** Ubuntu
**Version:** 20.04
**NodeJS version:** v16.13.0 (yarn 1.22.17)
**NGINX version:** 1.18

I generated the shared secret using `openssl rand -base64 24` and put that inside the sharedSecret section of `production.json`. I'm not sure if that's the location of the problem but seems likely considering it throws on the callback of authentication.

**Comment by PhlexPlexico** [comment]
I do believe it is shared secret that is a 16 byte key. I should have probably explained this one a bit better and not gonna lie, I just use random.org to generate a 16byte hexadecimal (remove the spaces) to place on that line 😅 I've really only used 16 bytes, so I can't really attest to the 24 or 32 byte usage. I would say maybe make sure there are no spaces. So a 16 byte key would have 32 characters I suppose.

**Comment by PhlexPlexico** [comment]
Oh yeah, I just ran your command and I could see this maybe being an issue? I've only used hexadecimal to generate bytes 🤔 the cryptography is something I've been meaning to go back to especially in regards to storing passwords and whatnot to not require user IDs, but I suppose this is something that should be either explained more or added to the list... But anyways try something from https://random.org/bytes and do a 16 byte key and remove the spaces, that should do it 😅

**Comment by Shaneajm** [comment]
Using a 16-byte key still results in the same issue.

**Comment by PhlexPlexico** [comment]
Yeah no, that shouldn't matter... I would say make sure the secret is in quotes, has no spaces, and is hexadecimal and lowercase maybe?  An example would be `"7304674bd18e7e300a66f3eabc086344"`

**Comment by Shaneajm** [comment]
`"sharedSecret": "7304674bd18e7e300a66f3eabc086344",`

Still getting this error:
```
GET /auth/steam 302 68.412 ms - 0
::ffff:127.0.0.1 - - [21/Nov/2021:06:16:21 +0000] "GET /auth/steam HTTP/1.1" 302 0 "https://g5.viquity.pro/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
Error: invalid key size (must be 16, 24 or 32 bytes)
    at AES._prepare (/home/shane/G5-API/node_modules/aes-js/index.js:206:19)
    at new AES (/home/shane/G5-API/node_modules/aes-js/index.js:198:14)
    at new ModeOfOperationOFB (/home/shane/G5-API/node_modules/aes-js/index.js:589:21)
    at Function.encrypt (/home/shane/G5-API/utility/utils.js:116:20)
    at /home/shane/G5-API/utility/auth.js:79:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERRORERRORERRORERRORERRORERRORERRORERROR Error: invalid key size (must be 16, 24 or 32 bytes)ERRORERRORERRORERRORERRORERRORERRORERROR
```
Very odd considering that said key should work.

**Comment by PhlexPlexico** [comment]
Oh wait sorry! This key I gave you should go to the dbKey 😅 https://github.com/PhlexPlexico/G5API/blob/c5d7c228a4a1bf657b754cb67791c54b3237276c/config/production.json.template#L5

That one there, my bad it's a bit late!

**Comment by Shaneajm** [comment]
All good! I thought I already had a 16 byte key there but I guess I didn't (oops!). It's letting me log in now.

Thanks for the help!

**Comment by PhlexPlexico** [comment]
Glad to hear! Anymore issues feel free to open a ticket 😄
