### ISSUE TITLE
[BUG] Issues when spinning G5API up with the docker-compose

### ISSUE THREAD

**Issue by stranden** [PhlexPlexico/G5API#148]
**Describe the bug**
I'm not able to start G5API at all, when using the docker-compose file.

After looking in the Docker log for the G5API container, I can see it is not able to run the db migration

$ MYSQL_FLAGS="-CONNECT_WITH_DB" db-migrate --env production --config config/production.json db:create get5
[ERROR] SyntaxError: Unexpected token g in JSON at position 52
    at JSON.parse (<anonymous>)
    at exports.parse (/Get5API/G5API/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/Get5API/G5API/node_modules/rc/index.js:30:20)
    at module.exports (/Get5API/G5API/node_modules/rc/index.js:46:20)
    at module.exports (/Get5API/G5API/node_modules/db-migrate/lib/commands/set-default-argv.js:122:47)
    at new dbmigrate (/Get5API/G5API/node_modules/db-migrate/api.js:75:10)
    at Object.module.exports.getInstance (/Get5API/G5API/node_modules/db-migrate/index.js:85:10)
    at /Get5API/G5API/node_modules/db-migrate/bin/db-migrate:32:25
    at /Get5API/G5API/node_modules/resolve/lib/async.js:133:25
    at maybeRealpath (/Get5API/G5API/node_modules/resolve/lib/async.js:41:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kdev** [comment]
This looks like a malformed `production.json`. 
Would you be able to share your `docker-compose.yml` file (please replace any tokens or domains with `<>` or similar)

**Comment by PhlexPlexico** [comment]
Heya!

Caught at a funny time here - I'm just working on getting docker-compose working with armv7 (for raspberry pis). There is going to be some instability here as seen in the last few commits, so please bear with me :) 

And yes, sharing the compose file would be very helpful, thank you!

**Comment by stranden** [comment]
Hi Guys,

I have tried to build the docker image by myself, and not use the existing docker image.

This is the docker-compose.yaml
I have removed the Caddy configuration because I use a NGINX instead.

`version: '2.1'

networks:
  get5:
    external: true

services:
  get5db:
    image: mariadb
    container_name: get5db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<>
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=
    ports:
      - "3306:3306"
    networks:
      - get5
  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    volumes:
      - redisVol:/RedisFiles
    expose:
      - 3301
    environment:
      - PORT=3301
      - HOSTNAME="get5.vibo.rush-b.dk"
      - DBKEY="<>"
      - STEAMAPIKEY="<>"
      - SHAREDSECRET="1234567890qwertyuiop"
      - CLIENTHOME="192.168.237.50"
      - APIURL="192.168.237.50/api"
      - SQLUSER=root
      - SQLPASSWORD=<>
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS="76561198077606052,76561197986415135"
      - SUPERADMINS="76561197991290317"
      - REDISPASSWORD=
      - UPLOADDEMOS=false
    restart: unless-stopped
    networks:
      - get5
  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
    container_name: G5V-Front-End
    restart: always
    networks:
      - get5

volumes:
  redisVol:
    external: false
`

We can close this issue, because it is working for me right now after building the container by hand

**Comment by PhlexPlexico** [comment]
```Dockerfile
- HOSTNAME="get5.vibo.rush-b.dk"
```

Above should include `https://` with no quotes.

```Dockerfile
- CLIENTHOME="192.168.237.50"
- APIURL="192.168.237.50/api"
```

These should be similar to the hostname.
```Dockerfile
- CLIENTHOME=https://get5.vibo.rush-b.dk
- APIURL=https://get5.vibo.rush-b.dk/api
```

And yeah if you're using NGINX to handle the SSL certs and whatnot you can just remove the Caddy dependency. I've been using a different reverse proxy, it's just there for easier setup. Here is my file that is currently working on my pi:

```Dockerfile
version: '2.1'

networks:
  get5:
    external: true

services:
  get5db:
    image: mariadb
    container_name: get5db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_here
      - MYSQL_DATABASE=get5
      - MYSQL_USER=get5
      - MYSQL_PASSWORD=password_here
    ports:
      - "3306:3306"
    networks:
      - get5

  g5api:
    image: ghcr.io/phlexplexico/g5api:latest
    depends_on:
      - get5db
    container_name: G5API
    volumes:
      - redisVol:/RedisFiles
    expose:
      - 3301
    environment:
      - PORT=3301
      - HOSTNAME=https://get5.phlexplexi.co
      - DBKEY=db_key
      - STEAMAPIKEY=api_key
      - SHAREDSECRET=a secure shared secret
      - CLIENTHOME=https://get5.phlexplexi.co
      - APIURL=https://get5.phlexplexi.co/api
      - SQLUSER=get5
      - SQLPASSWORD=<password>
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=
      - SUPERADMINS=76561198025644194
      - REDISPASSWORD=super_secure
      - UPLOADDEMOS=true
    restart: unless-stopped
    networks:
      - get5

  g5v:
    image: ghcr.io/phlexplexico/g5v:latest
    depends_on:
      - g5api
      - caddy
    container_name: G5V-Front-End
    restart: always
    networks:
      - get5

volumes:
  redisVol:
    external: false
```

This one should build without errors, quotes are not needed :)

**Comment by stranden** [comment]
Thanks @PhlexPlexico - you are awesome!
Love the explanation of hostname, clienthome and apiurl.

Because it works now, I'm gonna close this issue.

**Comment by PhlexPlexico** [comment]
Awesome. glad to hear it's working! :)
