### ISSUE TITLE
[Request] Maps player stats

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#155]
**Is your feature request related to a problem? Please describe.**
I am currently preparing some map statistics and doing it basically manually.

**Describe the solution you'd like**
Pulling how many maps were played from map_stats, and display it in leaderboards in frontend.

**Describe alternatives you've considered**
Getting access to DB and counting the valid entries that way.

**Comment by PhlexPlexico** [comment]
So you would just want this appended as a stat in the leaderboard calls? Or a different route specifically for the number of maps a user has played? I think I could just include it in the leaderboard stats.

**Comment by kubo6472** [comment]
> So you would just want this appended as a stat in the leaderboard calls?

Is there any way to do it per season?

**Comment by PhlexPlexico** [comment]
So I was finally able to look into this, but are you sure this is not already included? There's a `total_maps` in the leaderboard calls - https://phlex.avidgamers.me/api/leaderboard/players

So why don't you use this on a per player basis?

**Comment by kubo6472** [comment]
I've taken the stats I need from the database manually. I named the issue very wrongly. I was looking at the total number of played maps, not the individual players'.

**Comment by PhlexPlexico** [comment]
Wait so you're looking for just total number of maps played on the API? You can just use `/mapstats`, and I could just create a `/seasons/:season_id/mapstats` to give those and you can just parse the total data?

**Comment by kubo6472** [comment]
> Wait so you're looking for just total number of maps played on the API? You can just use `/mapstats`, and I could just create a `/seasons/:season_id/mapstats` to give those and you can just parse the total data?

Yep, I was looking for it in the frontend, between player statistics.

**Comment by PhlexPlexico** [comment]
I mean, I won't be including it as data in the front end since G5V is just supposed to be a general example of how to use the API. I think if you want to do this right now you can query the matches in a season, then query the mapstats with those match IDs to get a total count of maps played in a season?

**Comment by kubo6472** [comment]
Okay, thanks
