### ISSUE TITLE
[BUG] Matches ending 15-15 (Tie) gets canceled

### ISSUE THREAD

**Issue by stranden** [PhlexPlexico/G5API#158]
**Describe the bug**
Hi Phlex,

I have experienced that when a match in Bo1 without overtime ends 15-15, the match simple gets canceled.
The reason we are playing without OT is because of the tournament format.

Currently we are playing group stages were a win gives 3 points and a tie gives 1 point.

**To Reproduce**
1. Create a Bo1 with option "skip veto" and "never knife"
2. Play to 15-15 - The match ends on the server.

This is from the server log:

```
L 01/23/2022 - 19:49:26: get5_event: {
    "matchid": "10",
    "params": {
        "team1_score": 15,
        "winner": "none",
        "team2_score": 15,
        "map_number": 1,
        "map_name": "de_nuke"
    },
    "event": "map_end"
}
[RUSH-B.DK] OH WaldoPEEK and Monkey Brothers have tied the match.
```

**Expected behavior**
On /matches the status should be like this?
Tie, 15:15 vs Mads og Succes

**Screenshots**
[Match page](https://routes.dk/match/10)
![image](https://user-images.githubusercontent.com/18518722/150696408-5a5886bb-e4b8-4a77-83c9-7eb22395d621.png)

**Server info**
 - OS: [Debian]
 - Version [11]

**Docker Information**
I'm running docker both for G5V and G5API with a NGINX on another server for SSL offloading.
I did a git clone from master on both repos and did a docker build by myself

This is the ENV vars from the docker-compose file regarding G5API:

environment:
      - PORT=3301
      - HOSTNAME=https://routes.dk
      - DBKEY=
      - STEAMAPIKEY=
      - SHAREDSECRET=
      - CLIENTHOME=https://routes.dk
      - APIURL=https://routes.dk/api
      - SQLUSER=get5
      - SQLPASSWORD=
      - SQLPORT=3306
      - DATABASE=get5
      - SQLHOST=get5db
      - ADMINS=76561198077606052,76561197986415135,76561198001614536
      - SUPERADMINS=76561197991290317
      - REDISPASSWORD=
      - UPLOADDEMOS=false

**Comment by PhlexPlexico** [comment]
Good catch. Maybe seems to be something to do with this line here - 

https://github.com/PhlexPlexico/G5API/blob/d3051262b10d7d357a9ad3993a81bed7debb62e1/routes/legacy/api.js#L179

Since I guess that value should check if it's a BO2 match? I'm unsure as to what the finish call is called but it may be this messing things up. I won't be around for a few days but some testing may need to be done as well to ensure Bo2 works as well.

**Comment by PhlexPlexico** [comment]
This is fixed in the branch [here](https://github.com/PhlexPlexico/G5API/blob/faffd4b6d7cef6deffc9f331358604a5281754e9/routes/legacy/api.js#L179) to ensure that the match was actually cancelled by checking the scores as well :)

**Comment by stranden** [comment]
Hi Phlex,
I have just created the new container with the fix.
Looking forward to test it 💪
