### ISSUE TITLE
Install G5API YARN

### ISSUE THREAD

**Issue by Iwhite67** [PhlexPlexico/G5API#161]
Hello

i try to install you G5API with Yarn, but i got migrate-dev-create not found

![image](https://user-images.githubusercontent.com/9698964/151656146-d9de67f1-1e0a-4f12-bb71-5fe5884600cd.png)

allready try export NODE_ENV=production

**Comment by PhlexPlexico** [comment]
You're in the config directory. Try going up one directory to make sure you're in the same one where the `package.json` file exists :)

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/151664960-cc54f0ae-43f1-45d7-a81f-e3d20f2cfd34.png)


already test

**Comment by PhlexPlexico** [comment]
That's not the right command either. Please read inside the package.json file. If you're wanting to install the development database it's `yarn migrate-create-devThat's not the right command either. Please read inside the package.json file. If you're wanting to install the development database it's `yarn migrate-dev-create`.  These are the available scripts that you can run with the yarn command in this project, seen [here](https://github.com/PhlexPlexico/G5API/blob/d3051262b10d7d357a9ad3993a81bed7debb62e1/package.json#L30).

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/151665188-8e0aaf63-8dde-4087-8f17-0876dace6d52.png)

**Comment by Iwhite67** [comment]
i create a PR for fixe the syntaxe and keep a same logic for all command 

https://github.com/PhlexPlexico/G5API/pull/162
