### ISSUE TITLE
[Docker-Compose BUG] Funky parsing of admins & superadmins and db passwords

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#164]
**Additional context**
Hey, I love how you managed to use the containers to arrange the compose file. works great, except when specifying admins and superadmins and or db password. meaning: put "" into compose around admins and db password, api says invalid char in db connection string. but put them just around admins, and it won't connect to DB, too.

**Comment by PhlexPlexico** [comment]
If you have no values to input, just leave it blank within the docker-compose file.

https://github.com/PhlexPlexico/G5API/blob/d3051262b10d7d357a9ad3993a81bed7debb62e1/docker-compose.yml#L61

If super/admins are required, you do not need to use quotes in that file, everything should be treated like a string, so there shouldn't be a need for it. See an example [here](https://github.com/PhlexPlexico/G5API/pull/163#issuecomment-1030877792) in the PR that mentions this :)

**Comment by kubo6472** [comment]
SOLVED, do not use the custom URL, but rather steamid64 only. thanks for the time :)

**Comment by PhlexPlexico** [comment]
Ah yes, that as well is also in the [wiki](https://github.com/PhlexPlexico/G5API/wiki/Configuration#adminssuper-admins) glad it's solved :) anytime!

**Comment by kubo6472** [comment]
Oh, yeah. I see now. On bare metal deployment, the custom url worked for 
me, but since I use none of those now, that might have been for 
different reasons that happened in the meantime.
