### ISSUE TITLE
[Request] Force-setting in-game names to spectators

### ISSUE THREAD

**Issue by JesusWithPants** [PhlexPlexico/G5API#165]
1) Since get5 allows for forcing in-game names to spectators too, it would be useful to include and allow such functionality in G5API too.
2) On Season/Match creating - re-do spectator adding to also include forced names (so tournament ops can add necessary tags for example [ADMIN], [OBSERVER] etc).

**Comment by PhlexPlexico** [comment]
Huh, does it allow nicknames for spectators? Are you able to verify for that? If so, I can put it in the v1.5.0 so long as it can get tested :)

**Comment by PhlexPlexico** [comment]
As per the linked pull request it's implemented here. The public web panel is currently using this as well, but you may need to get a nice post request going since the front-end still isn't updated for that.

**Comment by JesusWithPants** [comment]
Will try within this week (once I have spare time).

**Comment by PhlexPlexico** [comment]
Public front end is now updated to handle spectator names. The format you must use is the following:

`<steam_identifier>;<nickname>`
Where `<steam_identifier>` can be any of the usual Steam IDs or a profile URL, then using a semi colon to separate it should allow you to use spectator names.
![image](https://user-images.githubusercontent.com/3514085/154128362-5a264ee0-30b2-433a-9a7e-5f9c5f58d093.png)

Just like that.

Thanks!
