### ISSUE TITLE
Yarn migrate create

### ISSUE THREAD

**Issue by Iwhite67** [PhlexPlexico/G5API#179]
Hello

when i put yarn migrate-create-prod, i have a error
![image](https://user-images.githubusercontent.com/9698964/160280086-cbb41d62-946b-446f-b06f-2c1eb33565d6.png)

![image](https://user-images.githubusercontent.com/9698964/160280104-52bfb418-b231-4086-8ad7-fa57643df431.png)

![image](https://user-images.githubusercontent.com/9698964/160280054-24939d36-90e6-400f-b31b-4b4325eb4244.png)

what is wrong ? i use mariadb on Ubuntu 20.04

**Comment by Iwhite67** [comment]
ok, is due to DB_Migrate not install, now is good

i have this on upgrade 
![image](https://user-images.githubusercontent.com/9698964/160282907-e02bfdfb-030d-483c-b2dc-81aaea31e284.png)

**Comment by PhlexPlexico** [comment]
Please make sure you have the latest version. If you do a `git status` (if you cloned the repo) and see we what the git hash is. There was a push the other week here where I removed some unused variables from a db migrate file and it did not like that :)

**Comment by Iwhite67** [comment]
![image](https://user-images.githubusercontent.com/9698964/160289211-e7f3798b-2793-406f-b46f-1bca35aa6f12.png)

same i git clone the main branch and i have this error

**Comment by PhlexPlexico** [comment]
Well, did you just call `yarn` at the start to install all dependencies?

**Comment by Iwhite67** [comment]
good thanks you, i continue to try to install API and vue (is hard xD)

**Comment by PhlexPlexico** [comment]
If you want (and know a bit of docker) that's easier to install to be honest. But if you follow the wiki you shouldn't have a problem installing. There may be some challenges with getting a reverse proxy working (Caddy is by far the easiest), but it shouldn't be too bad! Best of luck :)

**Comment by PhlexPlexico** [comment]
Going to close this for now, if you need help, feel free to create a [discussion](https://github.com/PhlexPlexico/G5API/discussions) as it may be easier to help there, rather than clogging up an issue.

Thanks!
