### ISSUE TITLE
[BUG] OOM Killer

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#180]
I know this is probably a very specific "me" issue, but I noticed that my VM randomly crashes and remaining running matches won't get thru (demos, matchFinished etc.). I found out, that `Out of memory: Killed process 49608 (node /Get5API/G) total-vm:11507952kB, anon-rss:218552kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:2220kB oom_score_adj:0` basically kills the API and then the whole system crashes. Is there any way there might be some memory leak or smth? Or a way this can be prevented? Btw. running in docker containers.

**Comment by PhlexPlexico** [comment]
If you're running containers, what's the specs of the host machine? 

I've seen instances that are still running and have not ran into any memory issues. In fact, it's quite light considering PM2 is indicating 28MB of usage at max.

**Comment by kubo6472** [comment]
Azure B1s: 1vCPU 1GiB RAM. Closing this as it surely isn't this program's fault.
