### ISSUE TITLE
[BUG] I have a problem on startup. How to solve it?

### ISSUE THREAD

**Issue by s1inche** [PhlexPlexico/G5API#191]
**Describe the bug**
I have a problem on startup. How to solve it?

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/54583646/164500639-66de8ff1-093d-442d-8b80-226f11d367e5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Server info**
 - OS:. Ubuntu
 - Version 16.04, 
 - NodeJS version 18.1.13

production.js - 
![noname](https://user-images.githubusercontent.com/54583646/164501136-59d3f7c4-3099-4448-bcf5-693ed413ee72.png)

**Comment by s1inche** [comment]
And please tell me where to register NODE_ENV

**Comment by PhlexPlexico** [comment]
If you're starting a production run, you should use the command `yarn startprod` as it will startup a PM2 instance for you and set your environment to production (i.e. `export NODE_ENV=production`).

Your steam ID for super_admins is also incorrect, you should be using a Steam64 ID (e.g. 76561198025644194).

Once you do that export, or run with `yarn startprod` it should start without issue. If you wish to access the logs, you can do so by calling `yarn pm2 logs G5API` while in the G5API directory!

Thanks!

**Comment by s1inche** [comment]
Спасибо большое! Это решило мою проблему! @PhlexPlexico

**Comment by s1inche** [comment]
![image](https://user-images.githubusercontent.com/54583646/164554792-91c04c5a-71f1-4bb7-82ba-f970925b6fde.png)
Hello. Still, I don't understand what I'm doing wrong. I sort of configured the nginx config. Do I need to create the same one for api.m0ve.fun? What folder on the server do I need to put in the config (api.m0ve.fun(nginx))?
Is it possible to use Docker for the web interface, and G5API itself on the server? - main question
Do I need to change the ''clientHome'' variable when using nginx?

Sorry for so many questions. But I would really like to install this ecosystem for myself (G5API + G5V)

**Comment by PhlexPlexico** [comment]
Heya,

For the nginx config, you can see the `/API/` block is meant for the API itself, so it would be hosted on `m0ve.fun/api/`.

The nginx config (if using nginx) I believe would go in `/etc/nginx/nginx.conf` on most releases. That's where that file would need to go.

You could run the web interface with docker, and then keep the proxy url in the Docker image to the localhost of the machine. I haven't done it before, but it should be possible :)

If you wanted the API to be on a subdomain (`api.m0ve.fun`), you would need to create another server block in the `nginx.conf` file.

Since you mentioned Docker, there is a docker compose file that runs the whole stack (Caddy as a reverse proxy, so nginx wouldn't be needed). I've been using it without issue.

Oh, and the `clientHome` variable is used for pointing back to the main front end. So if your API is `api.m0ve.fun` and your front end is `m0ve.fun` you would set the client home to `m0ve.fun`

Thanks!

**Comment by s1inche** [comment]
![image](https://user-images.githubusercontent.com/54583646/164729139-d91bd84c-f4e8-49ef-aa6b-98d03f809c4a.png)
Once again, good afternoon. It is normal that when cloning a database, it gives such errors. Although everything is correct.
And yet I don’t understand how G5API communicates and communicates with G5V

**Comment by PhlexPlexico** [comment]
Those are just warnings. I think there's a ticket open to fix some of the configs, but there is no issues, the database should be ok :)

The front end looks for a url (by default the url is `http://somehost.com/api`), and whenever it needs to retrieve, or send data it contacts that end point, hence the need for a reverse proxy (such as Caddy, Nginx, or Apache) to redirect the `/api/` calls to the API (which would technically be `http://somehost.com:3301` by default). 

The very technical aspect is that you have two servers running. One is a webserver on port 80 and 443 that will serve up the front end (you have to build it and place it in the web server directory). The second server is your Express NodeJS server that has all the logic in loading matches. This is the actual heart of the application.

To avoid opening up more ports to the world (like 3301), a reverse proxy is introduced on the web server (the same one that's running on port 80 and 443). This allows anyone to access the NodeJS server by going to a specific URL, which is by default `/api` (`http://somehost.com/api` -> `http://somehost.com:3301`). This is just good practice in general as it keeps the amount of ports open to the world at a lower number, and looks cleaner when trying to make calls.

I hope this helps!

**Comment by s1inche** [comment]
![image](https://user-images.githubusercontent.com/54583646/164732387-d17d1d81-858d-4ea3-a3e1-aa7d21affc73.png)
Thanks a lot for the explanation. May I ask?)
Is my nginx config configured correctly? I think if you answered this question, this ticket could become an example of files for those who in the future want to install this system for themselves.

I, as you advised, transferred the folder from the API to the G5V folder.
And now it turns out that I have G5V on the path - /var/www/html
A G5API - /var/www/html/api
-------------------------------------------------- ------------------------------------
![image](https://user-images.githubusercontent.com/54583646/164733324-579f963e-f835-4913-82db-7df4484b0d42.png)
When starting G5V, I have a vue.config.js file, do I need to change something in it? I didn't understand the instructions.

Thank you!

**Comment by s1inche** [comment]
Here's what I thought. I have a dist folder. Specify the path in the config to the dist folder, or still to the G5V root folder
![image](https://user-images.githubusercontent.com/54583646/164734073-da3c7362-610d-4f15-877f-cdd6647eccce.png)

**Comment by PhlexPlexico** [comment]
Okay, if you're running this all by hand I wouldn't exactly recommend it since configuration can be a bit difficult. I would highly recommend using the `docker-compose.yml` file in this project to setup the whole stack, and don't use NGINX. All you have to do with the `docker-compose` file is fill out the values that are listed in the README. However...

For the front end, you have to build the production build as mentioned [here](https://github.com/PhlexPlexico/G5V#production). The production files will be in that `dist` folder as mentioned.  You can ignore that file in your second screenshot, as it's used for development purposes only, and should absolutely not be used in a production environment.

Your NGINX config is not correct. Right now, your `location` block would be pointing to `http://m0ve.fun/var/www/api` to `localhost:3301`, that's not exactly what you want. So let's break this into steps:

1) In your `G5V` project. Run the following command: `yarn build` - this will build a production-ready end result of the project.
2) Your NGINX config shows that you are serving your files from `/var/www/html`. You're going to copy *everything* from inside your `dist` folder to `/var/www/html`
  2a) 
![image](https://user-images.githubusercontent.com/3514085/164735228-d3d398de-662b-4f2f-b964-e5a1f87baa20.png)

3) Change `location /var/www/api` back to `/api/`
4) In your **G5API** project, you want to start it and have it running in the background. This can be done via `yarn startprod` which will spin up an instance if there is not one running. I also noticed in your previous screenshot you did not give `redisPass` a value. Please give this a secure password.

Now that your front end is built and in the right directory, and you updated the web locations for the reverse proxy, restart nginx `sudo service restart nginx` and then navigate to `m0ve.fun` in your browser, it should load. If not, there may be some more configuration needed on your end with the API if it is not running properly.

**Comment by s1inche** [comment]
I realized that I'm too stupid to set everything up manually.(
As I understand it, you suggested using G5API via docker.

Do I need to create my own container? Or can you use the already created ones? like this - https://hub.docker.com/u/npflan

In theory, I can run G5API through docker, and G5V itself manually. Or do you need to run both through docker?

**Comment by PhlexPlexico** [comment]
`APIURL=http://get5.m0ve.fun/api` you need to have the full URL. That should fix it. Also if you don't want SSL, make sure to remove the port `443` from the Caddy config.

**Comment by s1inche** [comment]
I do not understand anything. I seem to have done everything right. And G5API in the docker configs loads fine and the database was created along with the tables and G5V seems to be working. But, when trying to login, nothing comes out and just a blank page remains, I already tried to reinstall docker and images. 

`{"log":"yarn install v1.22.18\n","stream":"stdout","time":"2022-04-22T19:34:12.17221761Z"}
{"log":"[1/6] Validating package.json...\n","stream":"stdout","time":"2022-04-22T19:34:12.820473587Z"}
{"log":"[2/6] Resolving packages...\n","stream":"stdout","time":"2022-04-22T19:34:12.834666343Z"}
{"log":"[3/6] Fetching packages...\n","stream":"stdout","time":"2022-04-22T19:34:14.897999936Z"}
{"log":"[4/6] Linking dependencies...\n","stream":"stdout","time":"2022-04-22T19:34:43.963198739Z"}
{"log":"warning \"swagger-jsdoc \u003e swagger-parser \u003e @apidevtools/swagger-parser@10.0.2\" has unmet peer dependency \"openapi-types@\u003e=7\".\n","stream":"stderr","time":"2022-04-22T19:34:43.969377467Z"}
{"log":"warning Workspaces can only be enabled in private projects.\n","stream":"stderr","time":"2022-04-22T19:34:44.023776283Z"}
{"log":"[5/6] Building fresh packages...\n","stream":"stdout","time":"2022-04-22T19:34:53.167138531Z"}
{"log":"[6/6] Cleaning modules...\n","stream":"stdout","time":"2022-04-22T19:35:04.105780943Z"}
{"log":"Done in 54.70s.\n","stream":"stdout","time":"2022-04-22T19:35:06.85380768Z"}
{"log":"yarn run v1.22.18\n","stream":"stdout","time":"2022-04-22T19:35:07.186877283Z"}
{"log":"$ MYSQL_FLAGS=\"-CONNECT_WITH_DB\" db-migrate --env production --config config/production.json db:create get5\n","stream":"stdout","time":"2022-04-22T19:35:07.293890811Z"}
{"log":"Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:07.69163726Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:07.692267325Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:07.692485415Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:07.692700099Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:07.692899149Z"}
{"log":"[INFO] Created database \"get5\"\n","stream":"stdout","time":"2022-04-22T19:35:07.72585748Z"}
{"log":"Done in 0.56s.\n","stream":"stdout","time":"2022-04-22T19:35:07.733785441Z"}
{"log":"yarn run v1.22.18\n","stream":"stdout","time":"2022-04-22T19:35:08.015596585Z"}
{"log":"$ db-migrate --env production --config config/production.json up:production\n","stream":"stdout","time":"2022-04-22T19:35:08.122763185Z"}
{"log":"Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:08.50642216Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:08.507123428Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:08.507386842Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:08.507663123Z"}
{"log":"Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection\n","stream":"stderr","time":"2022-04-22T19:35:08.507912854Z"}
{"log":"[INFO] No migrations to run\n","stream":"stdout","time":"2022-04-22T19:35:08.554869717Z"}
{"log":"[INFO] Done\n","stream":"stdout","time":"2022-04-22T19:35:08.556534772Z"}
{"log":"Done in 0.56s.\n","stream":"stdout","time":"2022-04-22T19:35:08.567304316Z"}
{"log":"yarn install v1.22.18\n","stream":"stdout","time":"2022-04-22T19:35:08.842594999Z"}
{"log":"[1/6] Validating package.json...\n","stream":"stdout","time":"2022-04-22T19:35:09.078735227Z"}
{"log":"[2/6] Resolving packages...\n","stream":"stdout","time":"2022-04-22T19:35:09.084155186Z"}
{"log":"[3/6] Fetching packages...\n","stream":"stdout","time":"2022-04-22T19:35:10.003844481Z"}
{"log":"[4/6] Linking dependencies...\n","stream":"stdout","time":"2022-04-22T19:35:11.396269599Z"}
{"log":"warning \"swagger-jsdoc \u003e swagger-parser \u003e @apidevtools/swagger-parser@10.0.2\" has unmet peer dependency \"openapi-types@\u003e=7\".\n","stream":"stderr","time":"2022-04-22T19:35:11.400586912Z"}
{"log":"warning Workspaces can only be enabled in private projects.\n","stream":"stderr","time":"2022-04-22T19:35:11.467150723Z"}
{"log":"[5/6] Building fresh packages...\n","stream":"stdout","time":"2022-04-22T19:35:21.331945095Z"}
{"log":"[6/6] Cleaning modules...\n","stream":"stdout","time":"2022-04-22T19:35:28.762348485Z"}
{"log":"Done in 24.25s.\n","stream":"stdout","time":"2022-04-22T19:35:33.087221384Z"}
{"log":"831:C 22 Apr 2022 19:35:33.124 # systemd supervision requested or auto-detected, but Redis is compiled without libsystemd support!\n","stream":"stdout","time":"2022-04-22T19:35:33.124906451Z"}
{"log":"yarn run v1.22.18\n","stream":"stdout","time":"2022-04-22T19:35:33.474274703Z"}
{"log":"$ pm2 start ./prodrun.json --name \"G5API\"\n","stream":"stdout","time":"2022-04-22T19:35:33.585191919Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071480158Z"}
{"log":"                        -------------\n","stream":"stdout","time":"2022-04-22T19:35:34.071557883Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071568682Z"}
{"log":"__/\\\\\\\\\\\\\\\\\\\\\\\\\\____/\\\\\\\\____________/\\\\\\\\____/\\\\\\\\\\\\\\\\\\_____\n","stream":"stdout","time":"2022-04-22T19:35:34.071598339Z"}
{"log":" _\\/\\\\\\/////////\\\\\\_\\/\\\\\\\\\\\\________/\\\\\\\\\\\\__/\\\\\\///////\\\\\\___\n","stream":"stdout","time":"2022-04-22T19:35:34.071611892Z"}
{"log":"  _\\/\\\\\\_______\\/\\\\\\_\\/\\\\\\//\\\\\\____/\\\\\\//\\\\\\_\\///______\\//\\\\\\__\n","stream":"stdout","time":"2022-04-22T19:35:34.071622089Z"}
{"log":"   _\\/\\\\\\\\\\\\\\\\\\\\\\\\\\/__\\/\\\\\\\\///\\\\\\/\\\\\\/_\\/\\\\\\___________/\\\\\\/___\n","stream":"stdout","time":"2022-04-22T19:35:34.071631888Z"}
{"log":"    _\\/\\\\\\/////////____\\/\\\\\\__\\///\\\\\\/___\\/\\\\\\________/\\\\\\//_____\n","stream":"stdout","time":"2022-04-22T19:35:34.071641829Z"}
{"log":"     _\\/\\\\\\_____________\\/\\\\\\____\\///_____\\/\\\\\\_____/\\\\\\//________\n","stream":"stdout","time":"2022-04-22T19:35:34.071651748Z"}
{"log":"      _\\/\\\\\\_____________\\/\\\\\\_____________\\/\\\\\\___/\\\\\\/___________\n","stream":"stdout","time":"2022-04-22T19:35:34.071661349Z"}
{"log":"       _\\/\\\\\\_____________\\/\\\\\\_____________\\/\\\\\\__/\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\_\n","stream":"stdout","time":"2022-04-22T19:35:34.071693325Z"}
{"log":"        _\\///______________\\///______________\\///__\\///////////////__\n","stream":"stdout","time":"2022-04-22T19:35:34.071703851Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071713391Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.07174067Z"}
{"log":"                          Runtime Edition\n","stream":"stdout","time":"2022-04-22T19:35:34.071780496Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071790379Z"}
{"log":"        PM2 is a Production Process Manager for Node.js applications\n","stream":"stdout","time":"2022-04-22T19:35:34.071799103Z"}
{"log":"                     with a built-in Load Balancer.\n","stream":"stdout","time":"2022-04-22T19:35:34.071807855Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071816548Z"}
{"log":"                Start and Daemonize any application:\n","stream":"stdout","time":"2022-04-22T19:35:34.071825081Z"}
{"log":"                $ pm2 start app.js\n","stream":"stdout","time":"2022-04-22T19:35:34.071833907Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071865028Z"}
{"log":"                Load Balance 4 instances of api.js:\n","stream":"stdout","time":"2022-04-22T19:35:34.0718743Z"}
{"log":"                $ pm2 start api.js -i 4\n","stream":"stdout","time":"2022-04-22T19:35:34.071883272Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071891898Z"}
{"log":"                Monitor in production:\n","stream":"stdout","time":"2022-04-22T19:35:34.071900616Z"}
{"log":"                $ pm2 monitor\n","stream":"stdout","time":"2022-04-22T19:35:34.071909429Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071918047Z"}
{"log":"                Make pm2 auto-boot at server restart:\n","stream":"stdout","time":"2022-04-22T19:35:34.071947584Z"}
{"log":"                $ pm2 startup\n","stream":"stdout","time":"2022-04-22T19:35:34.071957448Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071966045Z"}
{"log":"                To go further checkout:\n","stream":"stdout","time":"2022-04-22T19:35:34.071974636Z"}
{"log":"                http://pm2.io/\n","stream":"stdout","time":"2022-04-22T19:35:34.071983215Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.071991867Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.072000433Z"}
{"log":"                        -------------\n","stream":"stdout","time":"2022-04-22T19:35:34.072028534Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:34.072038796Z"}
{"log":"[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2\n","stream":"stdout","time":"2022-04-22T19:35:34.191730592Z"}
{"log":"[PM2] PM2 Successfully daemonized\n","stream":"stdout","time":"2022-04-22T19:35:34.602592764Z"}
{"log":"[PM2][WARN] Applications G5API not running, starting...\n","stream":"stdout","time":"2022-04-22T19:35:34.653777741Z"}
{"log":"[PM2] App [G5API] launched (1 instances)\n","stream":"stdout","time":"2022-04-22T19:35:34.693741301Z"}
{"log":"┌─────┬──────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐\n","stream":"stdout","time":"2022-04-22T19:35:34.875261589Z"}
{"log":"│ id  │ name     │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │\n","stream":"stdout","time":"2022-04-22T19:35:34.87541504Z"}
{"log":"├─────┼──────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤\n","stream":"stdout","time":"2022-04-22T19:35:34.875426635Z"}
{"log":"│ 0   │ G5API    │ default     │ 1.6.0.0 │ fork    │ 881      │ 0s     │ 0    │ online    │ 0%       │ 31.4mb   │ root     │ disabled │\n","stream":"stdout","time":"2022-04-22T19:35:34.875436336Z"}
{"log":"└─────┴──────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘\n","stream":"stdout","time":"2022-04-22T19:35:34.875492534Z"}
{"log":"Done in 1.44s.\n","stream":"stdout","time":"2022-04-22T19:35:34.901999853Z"}
{"log":"yarn run v1.22.18\n","stream":"stdout","time":"2022-04-22T19:35:36.150441441Z"}
{"log":"$ /Get5API/G5API/node_modules/.bin/pm2 logs\n","stream":"stdout","time":"2022-04-22T19:35:36.413737805Z"}
{"log":"[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)\n","stream":"stdout","time":"2022-04-22T19:35:37.314311091Z"}
{"log":"/root/.pm2/pm2.log last 15 lines:\n","stream":"stdout","time":"2022-04-22T19:35:37.337154488Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: PM2 version          : 5.2.0\n","stream":"stdout","time":"2022-04-22T19:35:37.341748526Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: Node.js version      : 16.5.0\n","stream":"stdout","time":"2022-04-22T19:35:37.342182603Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: Current arch         : x64\n","stream":"stdout","time":"2022-04-22T19:35:37.34260717Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: PM2 home             : /root/.pm2\n","stream":"stdout","time":"2022-04-22T19:35:37.343002282Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: PM2 PID file         : /root/.pm2/pm2.pid\n","stream":"stdout","time":"2022-04-22T19:35:37.343570422Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: RPC socket file      : /root/.pm2/rpc.sock\n","stream":"stdout","time":"2022-04-22T19:35:37.34395835Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: BUS socket file      : /root/.pm2/pub.sock\n","stream":"stdout","time":"2022-04-22T19:35:37.344358797Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: Application log path : /root/.pm2/logs\n","stream":"stdout","time":"2022-04-22T19:35:37.344765898Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: Worker Interval      : 30000\n","stream":"stdout","time":"2022-04-22T19:35:37.345155865Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: Process dump file    : /root/.pm2/dump.pm2\n","stream":"stdout","time":"2022-04-22T19:35:37.34568924Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: Concurrent actions   : 2\n","stream":"stdout","time":"2022-04-22T19:35:37.346065092Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: SIGTERM timeout      : 1600\n","stream":"stdout","time":"2022-04-22T19:35:37.346427394Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: ===============================================================================\n","stream":"stdout","time":"2022-04-22T19:35:37.346817334Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: App [G5API:0] starting in -fork mode-\n","stream":"stdout","time":"2022-04-22T19:35:37.347183353Z"}
{"log":"PM2        | 2022-04-22T19:35:34: PM2 log: App [G5API:0] online\n","stream":"stdout","time":"2022-04-22T19:35:37.349482079Z"}
{"log":"\n","stream":"stdout","time":"2022-04-22T19:35:37.349680739Z"}
{"log":"/root/.pm2/logs/G5API-out-0.log last 15 lines:\n","stream":"stdout","time":"2022-04-22T19:35:37.35321779Z"}
{"log":"/root/.pm2/logs/G5API-error-0.log last 15 lines:\n","stream":"stdout","time":"2022-04-22T19:35:37.357709848Z"}
`
![error](https://user-images.githubusercontent.com/54583646/164783689-3d9eab41-1998-4679-9855-bbc677cb972e.png)

**Comment by s1inche** [comment]
`get5_apistats.smx (Get5 Web API Integration): Required extension "System2" file("system2.ext") not running`


The get5_apistats.smx plugin sends this error. What to do?
I take from here - https://github.com/PhlexPlexico/get5-web/releases
