### ISSUE TITLE
[BUG] error	"Failed to verify assertion"

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#196]
randomly started happening now across both of my instances, probably steam error. can I reregisted without steam to avoid this?

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/168439751-78e44a2a-afe1-48df-8523-419ed8803303.png)
that wont work :/

**Comment by PhlexPlexico** [comment]
Chances are whenever this happens your server clock is not in sync with any time server. I'm assuming it's been closed as this was resolved?

**Comment by kubo6472** [comment]
This started happening for me on alk instances at one moment. For some reason it fixed itself moments later

**Comment by PhlexPlexico** [comment]
Yeah sounds like a clock sync issue, glad it's resolved :)
