### ISSUE TITLE
[BUG] error when starting API

### ISSUE THREAD

**Issue by tideodk** [PhlexPlexico/G5API#201]
**Describe the bug**
When running "yarn start" (I did copy the template to production.json)
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./bin/www.js`
WARNING: No configurations found in configuration directory:/home/G5API-1.6.0/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/home/G5API-1.6.0/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
          ^

Error: Configuration property "undefined.host" is not defined
    at Config.get (/home/G5API-1.6.0/node_modules/config/lib/config.js:182:11)
    at file:///home/G5API-1.6.0/db.js:6:16
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
[nodemon] app crashed - waiting for file changes before starting...

root@ubuntu-s-2vcpu-2gb-intel-fra1-01:/home/G5API-1.6.0# yarn migrate-create-prod && yarn migrate-prod-upgrade
yarn run v1.22.19
$ MYSQL_FLAGS="-CONNECT_WITH_DB" db-migrate --env production --config config/production.json db:create get5
Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
[INFO] Created database "get5"
Done in 0.37s.
yarn run v1.22.19
$ db-migrate --env production --config config/production.json up:production
Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisHost. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisPort. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisTTL. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
Ignoring invalid configuration option passed to Connection: redisPass. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection

**To Reproduce**
Install like told via the WIKI on Ubuntu 20.04

**Expected behavior**
The API should start up

**Server info**
 - OS: Ubuntu 20.04
 - Version 
 - NodeJS versionv14.18.1

**Comment by PhlexPlexico** [comment]
Please make sure you set your `NODE_ENV` to `production`, per the [wiki](https://github.com/PhlexPlexico/G5API/wiki/Configuration#starting-the-app) :)

Thanks!

**Comment by PhlexPlexico** [comment]
Also make sure you are using `pm2` and not `nodemon`, as the latter is used for development purposes only.

**Comment by PhlexPlexico** [comment]
Make sure it's enabled in your firewall settings, and usually you would use something like a reverse proxy (Caddy, NGINX, Apache, etc) to just route a web address to that port internally, so you wouldn't need to show it to the outside world.

Thanks!

**Comment by PhlexPlexico** [comment]
Make sure the app is running then, in the API directory you can check the logs with `yarn pm2 logs G5API`.

**Comment by tideodk** [comment]
> 

$ /Get5API/G5API/node_modules/.bin/pm2 logs G5API
[TAILING] Tailing last 15 lines for [G5API] process (change the value with --lines option)
/root/.pm2/logs/G5API-out-0.log last 15 lines:
/root/.pm2/logs/G5API-error-0.log last 15 lines:
0|G5API    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
0|G5API    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
0|G5API    |     at Module.load (internal/modules/cjs/loader.js:950:32)
0|G5API    |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
0|G5API    | Error: Cannot parse config file: '/Get5API/G5API/config/production.json': SyntaxError: Unexpected token , in JSON at position 28
0|G5API    |     at Config.util.parseFile (/Get5API/G5API/node_modules/config/lib/config.js:844:11)
0|G5API    |     at /Get5API/G5API/node_modules/config/lib/config.js:644:26
0|G5API    |     at Array.forEach (<anonymous>)
0|G5API    |     at Config.util.loadFileConfigs (/Get5API/G5API/node_modules/config/lib/config.js:643:16)
0|G5API    |     at new Config (/Get5API/G5API/node_modules/config/lib/config.js:116:27)
0|G5API    |     at Object.<anonymous> (/Get5API/G5API/node_modules/config/lib/config.js:1492:31)
0|G5API    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
0|G5API    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
0|G5API    |     at Module.load (internal/modules/cjs/loader.js:950:32)
0|G5API    |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)


I added you on steam. Maybe it is easier for you to diagnose my issue there - And then finally post it in here. I'm probably the issue :-)

**Comment by PhlexPlexico** [comment]
`0|G5API | Error: Cannot parse config file: '/Get5API/G5API/config/production.json': SyntaxError: Unexpected token , in JSON at position 28` This means that something in your config is amiss. You'll need to make sure that everything is correctly formatted, and I would prefer to diagnose issues here as it makes it easier for other users' to find resources if they have trouble!

Thanks!

**Comment by tideodk** [comment]
Hi!
I've formatted it like this:
{
  "server": {
    "port": ,
    "hostname": "http://url.com",
    "dbKey": "39b073daa3cc9b110732b34df7b0e36dxxxxxxxxx",
    "steamAPIKey": "F718691F8FD4F0D04BB601C3xxxxxx",
    "sharedSecret": "q123xxxxxx",
    "clientHome": "http://url.com:8080",
    "useRedis": true,
    "apiURL": "http://url.com:8080/api/",
    "uploadDemos": 
  },
  "production": {
    "driver": "mysql",
    "user": "get5_user",
    "password": "xxxxxx",
    "database": "get5",
    "multipleStatements": true,
    "flags": { "ENV": "MYSQL_FLAGS" },
    "host": "localhost",
    "port": ,
    "connectionLimit": 15,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisTTL": 86400,
    "redisPass": "xxxxx"
  },
  "admins": {
      "steam_ids": "STEAM_0:0:528xxxx"
  },
  "super_admins": {
    "steam_ids": "STEAM_0:0:528xxxxx"
  }
}

Position 28 lets me belive its the admins field. Is this not made correctly?

Please note that I used placeholders for the content.

**Comment by PhlexPlexico** [comment]
Yeah, the steam IDs are incorrect, as noted in [the wiki](https://github.com/PhlexPlexico/G5API/wiki/Configuration#adminssuper-admins) they are to be Steam64 IDs (e.g. 76561198025644194) inside the quotes, separated by commas.

Thanks!

**Comment by tideodk** [comment]
> 

Thanks again for your prompt answer. I edited it to the Decimal steam ID 64, and I am still getting the same issue


0|G5API    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
0|G5API    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
0|G5API    |     at Module.load (internal/modules/cjs/loader.js:950:32)
0|G5API    |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
0|G5API    | Error: Cannot parse config file: '/Get5API/G5API/config/production.json': SyntaxError: Unexpected token , in JSON at position 28
0|G5API    |     at Config.util.parseFile (/Get5API/G5API/node_modules/config/lib/config.js:844:11)
0|G5API    |     at /Get5API/G5API/node_modules/config/lib/config.js:644:26
0|G5API    |     at Array.forEach (<anonymous>)
0|G5API    |     at Config.util.loadFileConfigs (/Get5API/G5API/node_modules/config/lib/config.js:643:16)
0|G5API    |     at new Config (/Get5API/G5API/node_modules/config/lib/config.js:116:27)
0|G5API    |     at Object.<anonymous> (/Get5API/G5API/node_modules/config/lib/config.js:1492:31)
0|G5API    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
0|G5API    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
0|G5API    |     at Module.load (internal/modules/cjs/loader.js:950:32)
0|G5API    |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)

xx as placeholders.

  "admins": {
    "steam_ids": "765611980659528xx"
  },
  "super_admins": {
    "steam_ids": "765611980659528xx"
  }
}

**Comment by PhlexPlexico** [comment]
Glad to hear! :)
