### ISSUE TITLE
[BUG] Memory leaks, memory leaks everywhere

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#221]
**Describe the bug**
I have no idea why this would happen, but bin/www.js is eating at my memory based on data from top.
![image](https://user-images.githubusercontent.com/26146502/186667995-fbcecce0-0e35-422e-8e3e-b30ebeb12546.png)

**To Reproduce**
1. Open system monitor
2. Observe memory usage

**Expected behavior**
As @PhlexPlexico said, something more lightweight, or even closer to values from pm2, a.k.a. around 50mb of memory usage.

**Docker Information**
Docker 19.x from a compose file on Debian-based system on a Digital Ocean VPS.

**Additional context**
To do my part on the debugging, I tried running the code locally on a linux system, without docker, to eliminate it as a variable. Next I have tried eliminating pm2, swapping it for forever and back to pm2, then running raw node ./bin/www.js just to eliminate that part as well. Always locally and building a docker image and testing that in two different environments. After about 6 hours spent on this alone, I have no idea how to solve this.

**Comment by PhlexPlexico** [comment]
And there's nothing coming out of the logs themselves either that stands out of the ordinary? No warnings, or anything (aside from deprecation warnings)? 

Also, that appears to be only *virtual* memory that is causing this issue, which seems to be not a big [concern](https://stackoverflow.com/questions/23187228/what-is-virt-column-in-htop-memory-overhead). The actual memory being used is 39152bytes(I believe?).

If it's running and the OS seems to be working just fine (i.e. everything is not slow), then I wouldn't worry so much about it, by the sounds of it.

**Comment by kubo6472** [comment]
The problem is, that the OS is running significantly slower, and even halts for brief moments. The DB error that you saw has no explanation, but does not appear since. So maybe a fluke? I have since recreated the DB just to be sure I got rid of it.

**Comment by PhlexPlexico** [comment]
Could this be because you have a low swap as well? And also I'm unsure why you have so many instances running? There should only be one running at a time here, unless you're trying to run multiple APIs in roundrobin?

**Comment by kubo6472** [comment]
> Could this be because you have a low swap as well? And also I'm unsure why you have so many instances running? There should only be one running at a time here, unless you're trying to run multiple APIs in roundrobin?
> 
> Also, would you mind trying to sh into your container and run top, and show the output?
> 
> `docker container exec -it G5API sh` then `top` in there, paste the contents or screenshot :)

I was aiming just for one api running :)

**Comment by kubo6472** [comment]
Funny that you mention this though, since every single service in compose seems to have multiple processes with the same namr running.

**Comment by kubo6472** [comment]
> Could this be because you have a low swap as well? And also I'm unsure why you have so many instances running? There should only be one running at a time here, unless you're trying to run multiple APIs in roundrobin?
> 
> Also, would you mind trying to sh into your container and run top, and show the output?
> 
> `docker container exec -it G5API sh` then `top` in there, paste the contents or screenshot :)

![image](https://user-images.githubusercontent.com/26146502/186891093-4b185c91-15ac-4bf2-9caf-d82c8d187d47.png)

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/186898018-e659ac29-dd52-4ace-91b9-01f83cfadd36.png)
there is no swap by default

**Comment by PhlexPlexico** [comment]
So, no swap is going to cause issues first off on most OS', but that's a problem for another time. `htop` indicates you have more than one container running. Can you do `docker container ls` and see if there is more than one running? What's your config look like, have you made any modifications to the project? Does this only happen on Debian?

**Comment by kubo6472** [comment]
AFAICT docker container ls or docker ps as I did it till now shows only one container for each service yet top/htop show multiple identical processes. No modifications to the project, just ported the compose to another one and did that traefik thing, I tried it without that, stock file, different oses, different hosts, everywhere the same.

**Comment by PhlexPlexico** [comment]
Inside the container, would you mind calling `cat /proc/meminfo`? If `yarn pm2 status` is only showing a few hundred megabytes, that should be fine. As I said before, Virtual Memory is just the address space reserved by the program, it shouldn't be slowing anything down. That 10.3GB is pretty much meaningless :) what's the specs of the VPS that you're running?

Thanks!

**Comment by kubo6472** [comment]
Sure, sorry for the delay. I since moved to something beefier and it does not slow down at all. I am sure this one has at least half a gig of SWAP on hand, so it might have been just that.

```
/Get5API # cat /proc/meminfo
MemTotal:        8154876 kB
MemFree:         3631344 kB
MemAvailable:    7483684 kB
Buffers:          260148 kB
Cached:          3292952 kB
SwapCached:            0 kB
Active:           654684 kB
Inactive:        3400452 kB
Active(anon):       1180 kB
Inactive(anon):   452124 kB
Active(file):     653504 kB
Inactive(file):  2948328 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:        524284 kB
SwapFree:         524284 kB
Dirty:                76 kB
Writeback:             0 kB
AnonPages:        502080 kB
Mapped:           349648 kB
Shmem:              1984 kB
KReclaimable:     356496 kB
Slab:             406572 kB
SReclaimable:     356496 kB
SUnreclaim:        50076 kB
KernelStack:        7808 kB
PageTables:        12360 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     4601720 kB
Committed_AS:    3061848 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       19868 kB
VmallocChunk:          0 kB
Percpu:             2512 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      141160 kB
DirectMap2M:     8247296 kB
DirectMap1G:     2097152 kB

```

**Comment by PhlexPlexico** [comment]
Considering there is still roughly 7.5GB available, I would think maybe just introducing a swap on the lower spec machine may help as it would avoid disk thrashing. So yeah, I don't believe there is any memory leaks :)

**Comment by kubo6472** [comment]
Thanks
