### ISSUE TITLE
[Request] Demos folder

### ISSUE THREAD

**Issue by Bunker56** [PhlexPlexico/G5API#223]
There is such a proposal - to create a demos folder in the public folder, except for the backups and img folders, so that all files lie neatly, of course, you can get out of the situation with the help of volumes, but it would be more interesting to have all this "out of the box".

**Comment by PhlexPlexico** [comment]
I would just assume that the entire root area of the public folder is for demos only, does this not suffice? You could even write a script that just checks for zip files in that directory, and that would extract all the demos. Nothing else is supposed to be in that root directory anyways, aside from the other fodlers?

**Comment by Bunker56** [comment]
Logically...

**Comment by PhlexPlexico** [comment]
No reason to keep this closed either. PRs are welcome to adjust this, it just needs a bit more work than a single file change is all :)
