### ISSUE TITLE
[BUG] error in MKDIR Backup

### ISSUE THREAD

**Issue by Iwhite67** [PhlexPlexico/G5API#229]
![image](https://user-images.githubusercontent.com/9698964/192161324-82b262b6-872e-42b2-8773-659282493b7d.png)

**Comment by PhlexPlexico** [comment]
I can't recreate this for the life of me. I need some more information on your setup, as I think this may be setup dependent. 

Are you using a volume mount for `public`? Does this directory have write permissions? If you bash into this container, do you have a `public` directory? Following that, do you have a `backup` folder below that public path? This looks more like an issue with file writes.

Thanks!

**Comment by Iwhite67** [comment]
this is right, i have create missing folder, i will check if is working
