### ISSUE TITLE
[Request] Use get5 logging, demo, and backup systems

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#238]
**Is your feature request related to a problem? Please describe.**
Currently a whole different plugin was required in order to track stats across to an API for get5. This is no longer the case, as HTTP calls and headers are now setup to point to a single route. While it's unfortunate that it is only single route, we can now retrieve values without the use of G5WS.
**Describe the solution you'd like**
Finally deprecate the legacy API in favour of these new features in get5.

**Describe alternatives you've considered**
This can also be done in a step-by-step process. For now, we can focus on stat collection (and fix a few of the remaining bugs like stats when a match is restored), then move onto demo uploads, then backups.

**Additional context**
This should allow us to standardize this project without the use of additional plugins. Server setup would be as simple as setting up get5, then adding the server to the API. The rest should be taken care of.

We should also note that we should deprecate G5WS now, which means maybe leave a message or something on match creation that states if G5WS is being used. If G5WS (`get5_web_available`) is present on the game server, we should still be using that first, since it still is the most stable.

**Comment by Bunker56** [comment]
I completely agree with you. That would be just fine.

**Comment by PhlexPlexico** [comment]
Closing for #249
