### ISSUE TITLE
[Request] V2 API

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#249]
**Is your feature request related to a problem? Please describe.**
Currently the API is broken for anything above 0.14 for get5, this was due to the changes in the events that were being sent over.

**Describe the solution you'd like**
We should now finally deprecate the old API in favour of a `/v2` route. This new route should only use the basic get5 functions, that way the old G5WS plugin could be retired as well. A good chunk of code can be copied over as functions, aside from the following events:
- [x] Get5_OnMapResult -> The teams are now in the JSON, we could possibly utilize this instead of making more database calls.
- [x] Remove `UpdateRoundStats` in favour of live updates with the usage of: 
    - [x] `Get5_OnPlayerDeath`
    - [x] `Get5_OnPlayerBecameMVP`
    - [x] `Get5_OnBombPlanted`
    - [x] `Get5_OnBombDefused`
- [x] Use various live stats to include new event emitters to allow for "Live" updates when a user is listening.
- [x] Utilize `Get5_OnBackupRestore` to remove any data that may be invalid - such as removing Additional Stats for rounds that were now not played out, and updating the Kills/Death/Damage/etc.
- [ ] Utilize the values for the Live events, such as `Get5_OnGrenadeThrown`, etc. to give more data to external systems. However, this one is very pie-in-the-sky for now and may not be added.

**Additional context**
A good thing about this is that there isn't a lot to fix. Most of the work will be attempting to make the design a bit more clean. Instead of dumping the DB logic/etc all in a single file, we should move the core logic out into separate files based on the call, and then call them in the single route via a case statement. 

Another thing to consider is the demo uploads - we can now utilize get5 to set the upload header key and value to the API key that is generated via the API for the match, no more hacky storing the API key until the demo is finished.

- [X] One other check that will have to be done is to check for `get5_web_available`. Since this is not native to get5, we should always check for the version first, and if we are on anything greater than 0.14, we can ignore the checks to see if G5WS is included.

Hopefully with the current way I'm thinking we can seamlessly integrate 0.14 and still have 0.13 and less used with G5WS... However G5WS only has support for 0.13, so we will eventually have to just remove it outright.

**Comment by Bunker56** [comment]
Started... I'll unsubscribe a little later. By the way, a small error in the program.json - "script": "./dist/bin/www.js ", - "/dist" superfluous

**Comment by PhlexPlexico** [comment]
**Definitely** not usable as of right now :) it's something I'm going to continue chipping away at, as you can see the v2 api is currently empty and I'm just starting to work on the typing. I'm still considering the layout and logic of using a single route for multiple calls.

This will probably take quite a bit to make something "work"... While I want to make something usable I still have some real life responsibilities and other distractions. However, it would definitely be helpful to have someone test it out once it comes to that state!

**Comment by Bunker56** [comment]
[PM2][ERROR] Error: Script not found: /Get5API/dist/bin/www.js

**Comment by Bunker56** [comment]
At least now the server status is already green..:)

**Comment by PhlexPlexico** [comment]
Hi @Bunker56 

The map and series flows are finished, so G5API should now be able to read stats and everything from 0.14 onward. It's on the package `next` or `2.0.0.0` if you're building from Docker. Feel free to test it out and let me know if the match stat collection is working. 

The only things left to do are demo uploads and remote backups, those won't be implemented yet so you may receive errors on get5 stating that these don't exist.
