### ISSUE TITLE
[BUG] Yarn start does not work in development

### ISSUE THREAD

**Issue by Shaneajm** [PhlexPlexico/G5API#250]
**Describe the bug**
I'm attempting to launch the API in development mode but running `yarn start` causes the app to crash with an error:

```
throw new Error('Configuration property "' + property + '" is not defined');
          ^

Error: Configuration property "undefined.host" is not defined
```

**To Reproduce**
1. Clone Repo
2. `yarn install`
3. Run migrations/setup
4. Configure `development.json` file
5. Run `yarn start`

**Expected behavior**
Go into a development mode that allows hot-reloading, etc.

**Desktop (please complete the following information):**
 - OS: `Windows 11 Pro`
 - Browser: `Firefox`
 - Version: `113.0.2`

**Server info**
 - OS: `Windows`
 - Version: `Master Branch Clone`
 - NodeJS version: `18.14.2`

**Additional context**
I have attempted the same setup on a PopOS 22.04 install and the latest Node 18 LTS release with the same issue.

**Comment by Shaneajm** [comment]
I was missing `$env:NODE_ENV="development"`. That fixed the problem! 😅

**Comment by PhlexPlexico** [comment]
Glad to hear you got it working!
