### ISSUE TITLE
URLs not being set properly

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#252]
this is a piece of the log with an error that was in the previous API, the API logs are fine, there are no errors
BNK#3: !r
L 06/24/2023 - 18:27:12: "BNK#3<3><STEAM_1:1:537158178><TERRORIST>" say "!r"
_**src/common/httpclient.cpp (808) : pHost && *pHost**_
src/common/httpclient.cpp (808) : pHost && *pHost
L 06/24/2023 - 18:27:12: [get5.smx] Event HTTP request failed due to a network or configuration error. Make sure you have enclosed your event URL in quotes.
BNK#1: !r
L 06/24/2023 - 18:27:26: "BNK#1<6><STEAM_1:1:537225542><CT>" say "!r"
_**src/common/httpclient.cpp (808) : pHost && *pHost**_
src/common/httpclient.cpp (808) : pHost && *pHost
L 06/24/2023 - 18:27:26: [get5.smx] Event HTTP request failed due to a network or configuration error. Make sure you have enclosed your event URL in quotes.

_Originally posted by @Bunker56 in https://github.com/PhlexPlexico/G5API/issues/251#issuecomment-1605613350_

**Comment by PhlexPlexico** [comment]
@Bunker56

Please post the following from your game server when the match is created via rcon or the game server console:

`get5_remote_log_url`
`get5_remote_backup_url`
`get5_demo_upload_url`

**Comment by Bunker56** [comment]
OK

**Comment by PhlexPlexico** [comment]
Okay the new image is building, I think I forgot to enclose the URLs so this latest push should fix it. Just wait for the image to finish building and then update as needed and try again!

**Comment by Bunker56** [comment]
I played the series, the veto worked, but it's a little strange that the desider map appeared twice in the list, statistics are not written. I decided not to bother, here are the full logs of the played series.

https://g5test.bunker56.ru/match/5 - The match itself
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11858099/csgoserver-console.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11858100/G5API-error-0.log)

maybe I made a mistake somewhere or didn't catch up...

**Comment by PhlexPlexico** [comment]
Perfect, thanks for these :) I can now get to some bug fixing here.

**Comment by PhlexPlexico** [comment]
Okay, would you mind updating your docker-compose to use `next` instead of `latest`? This new image should fix the issues you were having.

**Comment by PhlexPlexico** [comment]
Okay, I've made one other change to include some more logging on the events being sent to the API. Could you please run another test, even a short match to see if we can get some more information?

If so, could you also run `get5_debug 1` before the match as well as `get5_pretty_print_json 0` and send the logs of the match again please? It would be extremely helpful :)

**Comment by Bunker56** [comment]
**docker pull ghcr.io/phlexplexico/g5api:next**
no veto record, no statistics record. after the veto, the recording of the results stops, the score is 0:0
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11859043/csgoserver-console.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11859044/G5API-error-0.log)

**Comment by Bunker56** [comment]
**build from dep-updates branch**
no veto record, no statistics record. after the veto, the recording of the results stops, the score is 0:0
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11859048/csgoserver-console.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11859049/G5API-error-0.log)

**Comment by Bunker56** [comment]
**build from master branch**
there is a record of the veto, but the map sender is duplicated, there is no record of statistics , there is a total score (1:0)
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11859061/csgoserver-console.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11859062/G5API-error-0.log)

**Comment by PhlexPlexico** [comment]
Could you also provide the regular log file from the API, not just the error log? There's some debug information in those that I need. Thanks!

**Comment by Bunker56** [comment]
for which of the options?

**Comment by PhlexPlexico** [comment]
Nevermind actually, the game logs with get5_debug 1 were perfect enough for me to test. I've squashed the bug with the header errors. I think there may still be some outlying SQL errors, but the latest push to `dep-updates` should work way better than the main branch. If you give it about 10 minutes you should be able to pull `next` again from the docker-compose and should be able to test once more! :)

Thanks for all the help, it means a lot!

**Comment by Bunker56** [comment]
No problem.

**Comment by Bunker56** [comment]
https://g5test.bunker56.ru/match/11
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11860988/csgoserver-console.log)
[errors_20230626.log](https://github.com/PhlexPlexico/G5API/files/11860989/errors_20230626.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11860990/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11860991/G5API-out-0.log)
[L20230626.log](https://github.com/PhlexPlexico/G5API/files/11860992/L20230626.log)

**Comment by PhlexPlexico** [comment]
Hah! Thanks for pointing that out - I was so focused on updating player stats that I forgot to increment the map stats scores when the API call came in. Okay, well it's looking like there are less errors as well, which is good! Although it seems the demo upload failed. Could you please check `src/public/` and see if anything exists in there? Thanks!

**Comment by Bunker56** [comment]
There is a demo in src/public/, but not in the demos folder

**Comment by Bunker56** [comment]
One more screen... The same match
![Screenshot_6](https://github.com/PhlexPlexico/G5API/assets/91856368/1a884208-007f-4f7b-8e4f-2469c77035f6)

**Comment by PhlexPlexico** [comment]
Ahhh okay! So my suspicion was right - I need to get to the root of the project now, and not under `src`.

And yes, I just realized that I missed implementing the `round_end` event. Just making a few changes and it should be available to test once more shortly :)

**Comment by PhlexPlexico** [comment]
Alright, new `next` tag should be up in 5-10 minutes, I think everything you've shown should be fixed now!

**Comment by Bunker56** [comment]
Now working!.. Demo recording, but not archived in zip
**BO1**
https://g5test.bunker56.ru/match/12
**BO3**
https://g5test.bunker56.ru/match/13
And little bug in stats...
![Screenshot_7](https://github.com/PhlexPlexico/G5API/assets/91856368/2cbab000-2585-40d1-87bd-b7d774870c9c)

**Comment by Bunker56** [comment]
In the previous version was "Ban" title
![Screenshot_8](https://github.com/PhlexPlexico/G5API/assets/91856368/dfc2cd3d-a11d-4665-a852-2634eadd6d4c)

**Comment by Bunker56** [comment]
if necessary, I can play another series and send logs...

**Comment by Bunker56** [comment]
One more match,,,
New docker image
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11868799/csgoserver-console.log)
[errors_20230626.log](https://github.com/PhlexPlexico/G5API/files/11868800/errors_20230626.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11868801/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11868802/G5API-out-0.log)
[L20230626.log](https://github.com/PhlexPlexico/G5API/files/11868803/L20230626.log)

**Comment by Bunker56** [comment]
oops!.. somehow fast for 4 rounds, or does it seem to me?
![Screenshot_12](https://github.com/PhlexPlexico/G5API/assets/91856368/ad9545aa-6dc9-41a8-a4c7-bd4709b939c9)

**Comment by PhlexPlexico** [comment]
Perfect, looks like things are working forf the most part!

The front end needs to be updated because it's looking for `bsn` in the database, but I decided to make things universal and use `veto` instead. So that's something small.

The map selection is just an issue with some logic in how those are determined. The old plugin used to send what map is being played during the map start call, but no longer does that so we have to deduce it based on the information we got. Since you're using the in game veto system, it should be picking that up but I guess there is an error in my SQL query.

K/D difference seems odd, I'll take a look.

And timing wise the start time begins on map start and map end, it's possible for 4 rounds to be completed in a short time frame, but I'll look :)

**Comment by PhlexPlexico** [comment]
Okay, the latest push to that branch and `next` on the docker image should have fixed everything that has been reported, and G5V has been updated as well to show "ban" if "veto" or "ban" exist in the database! Feel free to give it a go!

**Comment by Bunker56** [comment]
I'm getting started.

**Comment by Bunker56** [comment]
Voila!..

![Screenshot_13](https://github.com/PhlexPlexico/G5API/assets/91856368/ed5da314-d7c9-46ca-9faf-ce9057bd6810)
![Screenshot_14](https://github.com/PhlexPlexico/G5API/assets/91856368/4851e9fc-e9ca-4bb2-9872-5776884708ac)

[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11873449/csgoserver-console.log)
[errors_20230627.log](https://github.com/PhlexPlexico/G5API/files/11873450/errors_20230627.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11873451/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11873452/G5API-out-0.log)
[L20230627.log](https://github.com/PhlexPlexico/G5API/files/11873454/L20230627.log)

**Comment by Bunker56** [comment]
[get5] HTTP response body: {"message":"Unknown column 'player_stat_id' in 'field list'"}
Is something wrong with me?

**Comment by PhlexPlexico** [comment]
Nope, that's something I need to take care of! One second here :)

**Comment by Bunker56** [comment]
No problem.

**Comment by PhlexPlexico** [comment]
Alright, latest change is pushed, should be available in about 10 minutes once the image builds!

**Comment by Bunker56** [comment]
OK, lets try,,,

**Comment by Bunker56** [comment]
8 maps, 2 overtimes,, it`s OK.
![Screenshot_15](https://github.com/PhlexPlexico/G5API/assets/91856368/47e39dd6-4f77-47e9-a943-d92258c3964f)
![Screenshot_16](https://github.com/PhlexPlexico/G5API/assets/91856368/8d21de6b-4f28-4dd3-a03d-097350bf23d2)

https://g5test.bunker56.ru/match/16
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11874914/csgoserver-console.log)
[errors_20230627.log](https://github.com/PhlexPlexico/G5API/files/11874917/errors_20230627.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11874918/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11874919/G5API-out-0.log)
[L20230627.log](https://github.com/PhlexPlexico/G5API/files/11874920/L20230627.log)

**Comment by PhlexPlexico** [comment]
Pertfect! Looking at the logs there is still a few events complaining after the match has finished, but that isn't really a problem. Looks like this should be good to move forward and release!!

Thank you very much for all the help :)

**Comment by Bunker56** [comment]
What about Wingman ? ;)

**Comment by PhlexPlexico** [comment]
As for right now, I believe usage of `cvars` should be sufficient to set the game up for wingman :)

**Comment by Bunker56** [comment]
> usage of `cvars`

Front-end?

**Comment by PhlexPlexico** [comment]
![image](https://github.com/PhlexPlexico/G5API/assets/3514085/1930f773-e6e9-4106-898d-13694c98c588)
Just in the CVARs there - put in the cvar you wish then hit tab to complete it :)

**Comment by Bunker56** [comment]
set_wingman 1 ?

**Comment by PhlexPlexico** [comment]
I mean, that's just an example, not an actual CVAR. You will have to set your cvars there - right now there is no support for get5's `wingman` in the config - and I'm unsure if it's something I want to spend time implementing either

**Comment by Bunker56** [comment]
logically. By the way, there is no point, it can do with a plugin like "Blocker Plant"

**Comment by PhlexPlexico** [comment]
Well, I probably won't touch the front-end, but I'll try my hand at making something on the API that can support the `wingman` option in the match config. How about that?

**Comment by Bunker56** [comment]
Why not? Let`s try...

**Comment by PhlexPlexico** [comment]
Front end was easier than expected,it should be in there to toggle when creating matches now :)

**Comment by Bunker56** [comment]
Waiting for the new version API?  :)

**Comment by Bunker56** [comment]
It`s working!.. But something with stats
https://g5test.bunker56.ru/match/20
![Screenshot_18](https://github.com/PhlexPlexico/G5API/assets/91856368/94892904-b7ff-43f7-b3ff-3fc4d2aacc53)
![Screenshot_19](https://github.com/PhlexPlexico/G5API/assets/91856368/a5195bc1-b7bd-4a61-be41-90188db1b03d)
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11876324/csgoserver-console.log)
[errors_20230627.log](https://github.com/PhlexPlexico/G5API/files/11876325/errors_20230627.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11876327/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11876328/G5API-out-0.log)
[L20230627.log](https://github.com/PhlexPlexico/G5API/files/11876329/L20230627.log)

**Comment by Bunker56** [comment]
For the purity of the experiment, I will try to recreate the database and try again...

**Comment by PhlexPlexico** [comment]
I guess for BNK#3 what was their first action? Planting the bomb? Or a kill/death?

**Comment by Bunker56** [comment]
The latest g5api:next (Wingman match) 
![Screenshot_20](https://github.com/PhlexPlexico/G5API/assets/91856368/f56616c9-9003-4b87-b80b-eb38286ad88f)
https://g5test.bunker56.ru/match/1
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11881650/csgoserver-console.log)
[errors_20230627.log](https://github.com/PhlexPlexico/G5API/files/11881651/errors_20230627.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11881652/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11881653/G5API-out-0.log)
[L20230627.log](https://github.com/PhlexPlexico/G5API/files/11881654/L20230627.log)

**Comment by PhlexPlexico** [comment]
Okay, some more logging has been put in the app to find this rogue addition of kills. It appears headshot kills is working just fine, but regular kills isn't. Please pull from `next` in 10 minutes and see if we can find out where this is being set :)

**Comment by Bunker56** [comment]
![Screenshot_21](https://github.com/PhlexPlexico/G5API/assets/91856368/a850fe22-faec-49e4-86ee-85858fc624ca)
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11886160/csgoserver-console.log)
[errors_20230627.log](https://github.com/PhlexPlexico/G5API/files/11886161/errors_20230627.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11886162/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11886163/G5API-out-0.log)
[L20230627.log](https://github.com/PhlexPlexico/G5API/files/11886164/L20230627.log)

**Comment by PhlexPlexico** [comment]
Okay, I think this may be coming down to a concurrency issue. I've added much more logging because I was unable to find the same result via Postman. Would you mind trying to run one last match and see if we can squash this bug? Worst case, I may take out the player stats update on death.

**Comment by Bunker56** [comment]
Just a moment...

**Comment by PhlexPlexico** [comment]
Okay, so it's looking like this is largely a concurrency issue with the round ending and players dying. I'll have to remove the calls to the `player_stats` updates during the `OnPlayerDeath` as this should fix the issue.

Also, as an aside, I see you're running into the error `[get5] Not uploading backup file as no URL was set.` - do you have `get5_remote_backup_url` set anywhere in your server config to nothing? Since the demo is uploading, the remote backups should work as well.

I'll let you know as soon as I have the patch out.

**Comment by Bunker56** [comment]
One more question is what kind of branch to use to build the g5v?

**Comment by PhlexPlexico** [comment]
Just use master, the wingman branch was merged into it a few days ago

**Comment by Bunker56** [comment]
I played another series, it was noticed that after the end of the first round, statistics are written normally, but at the end of the second, the value of kills increases by 1. A little later I will write the logs, replay them again and send the result....

**Comment by PhlexPlexico** [comment]
Well, did the user kill someone while you were looking? `OnPlayerDeath` will update the stats and automatically report it to the front end, providing love updates.

**Comment by Bunker56** [comment]
I played alone on two computers, so someone's interference is excluded...

**Comment by Bunker56** [comment]
and could it be a bug of get5, which version is better to use? I have 0.14.7 now.

**Comment by PhlexPlexico** [comment]
0.14.7 is the exact same as development, so there are no differences.

**Comment by Bunker56** [comment]
I have now played two matches in a row with the same parameters, got interesting results...
https://g5test.bunker56.ru/match/14
![Screenshot_23](https://github.com/PhlexPlexico/G5API/assets/91856368/dd05ef9c-fe71-44e7-86ef-172184da9e19)
https://g5test.bunker56.ru/match/15
![Screenshot_24](https://github.com/PhlexPlexico/G5API/assets/91856368/9ce3b4ac-10b2-48db-99b9-3dff7cb07a16)
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11900113/csgoserver-console.log)
[errors_20230629.log](https://github.com/PhlexPlexico/G5API/files/11900114/errors_20230629.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11900115/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11900116/G5API-out-0.log)
[L20230629.log](https://github.com/PhlexPlexico/G5API/files/11900117/L20230629.log)

**Comment by PhlexPlexico** [comment]
Okay, I've removed some more calls to inserting on playerstats. I think this is possibly a concurrency issue with the database doing inserts and when the API receives the call. Please try one last time :)

**Comment by PhlexPlexico** [comment]
It definitely has to do with order of events. When the player dies, has he planted the bomb prior to?

**Comment by Bunker56** [comment]
> When the player dies, has he planted the bomb prior to?
No, he's not doing anything, he's just standing there.

**Comment by PhlexPlexico** [comment]
Okay well make sure your API is updated, since I removed any inserts that just insert deaths. So I believe that shouldn't happen anymore.

**Comment by Bunker56** [comment]
Hi!
I probably owe you an apology for making you tense up. But I still didn't understand what the problem might be. I just transferred the API to a computer with CS GO servers, checked all the settings again, and, miraculously, everything works... It is possible that Debian 12 is installed on the computer where the API was installed, although I do not know if this is because of this. But on Debian 11 it seems to work without problems. Once again, I apologize for the inconvenience caused ...
I want to try to build my own API image for an experiment, can I use `master` branch or are there any nuances?

**Comment by PhlexPlexico** [comment]
Hey no worries! I'm sure there is still some concurrency issues based on what is being received, as you can see in the logs there's a few post calls line up close enough... Would you mind if I revert my changes to insert playerstats on death again and see if that works?

Thanks!

**Comment by Bunker56** [comment]
You're welcome!
But I'll probably still have to save the current `next` image...

**Comment by Bunker56** [comment]
I played BO 1, BO3, standard and wingman - everything works fine, statistics are written normally. And strangely enough, after transferring the IP to the CS GO server, the maps stop freez... Strange, but a fact.

**Comment by PhlexPlexico** [comment]
Well, it's a small change, it should *only* update if the playerstats record exists, so there shouldn't be any errors.

**Comment by Bunker56** [comment]
pull new `next`?

**Comment by PhlexPlexico** [comment]
Yes please!

**Comment by Bunker56** [comment]
Let`s try. :)

**Comment by Bunker56** [comment]
Cheating again... :)
![Screenshot_30](https://github.com/PhlexPlexico/G5API/assets/91856368/847440c1-3802-4b3e-a5fd-75d4706c260d)
[csgoserver-console.log](https://github.com/PhlexPlexico/G5API/files/11911183/csgoserver-console.log)
[errors_20230630.log](https://github.com/PhlexPlexico/G5API/files/11911184/errors_20230630.log)
[G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11911185/G5API-error-0.log)
[G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11911186/G5API-out-0.log)
[L20230630.log](https://github.com/PhlexPlexico/G5API/files/11911187/L20230630.log)

**Comment by PhlexPlexico** [comment]
Hmmm interesting, alright we'll remove that and call it a day then!

**Comment by Bunker56** [comment]
it seems to me that statistics will be quite enough for the frontend, for those who want a more capacious one, there is a plugin for MySQL.

**Comment by Bunker56** [comment]
Only backups are not written, everything else seems to work

**Comment by Bunker56** [comment]
Perfectly!..

![Screenshot_33](https://github.com/PhlexPlexico/G5API/assets/91856368/e3d03c5f-0e36-49e4-b220-388c01a865f4)
![Screenshot_34](https://github.com/PhlexPlexico/G5API/assets/91856368/522b9c2a-7918-490d-9403-0cfe2aa8bda8)

**Comment by PhlexPlexico** [comment]
Perfect, again thanks for bearing with all the testing! :)

**Comment by Bunker56** [comment]
You are always welcome, if you need anything, I am at your service

**Comment by Bunker56** [comment]
Hi! One more question...
I have not tried to use the backup system yet, and I would like to know if it is being used or if the functionality is not yet available?

**Comment by PhlexPlexico** [comment]
It should be available, just ensure that you don't set `get5_remote_backup_url` anywhere in your server configs. G5API automatically sets it itself and will backup game states under `public/backups`.

**Comment by Bunker56** [comment]
Game states under `public/backups` are not created, but they are essentially not needed after the match. During the match, everything works fine, backups are functioning

**Comment by Bunker56** [comment]
code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "INSERT INTO match_bomb_plants SET `match_id` = '23', `map_id` = 25, `player_stats_id` = 54, `round_number` = 0, `round_time` = 406>
  sqlState: '42S22',
  sqlMessage: "Unknown column 'bomb_time_remaining' in 'field list'"
}

**Comment by PhlexPlexico** [comment]
> Game states under `public/backups` are not created, but they are essentially not needed after the match. During the match, everything works fine, backups are functioning, Config get5 is default.

Yeah but there are remote backups that get5 will send to a web server every round. In the event of a server being unstable/crashing, you would be able to load the backup from the API server onto a new game server and continue from there. I may have to do some testing by myself to ensure this is working.

I've seen in your game server logs when it tries to write a backup it says that the `get5_remote_backup_url` is not set, even though the API sets it the same time the demo values are set. Could you start a game, pause it, and use the game server console to take a look at that value?

> Is this how it should be?
> 
> code: 'ER_BAD_FIELD_ERROR', errno: 1054, sql: "INSERT INTO match_bomb_plants SET `match_id` = '23', `map_id` = 25, `player_stats_id` = 54, `round_number` = 0, `round_time` = 40656, `site` = 'a', `defused` = true, `bomb_time_remaining` = 18430", sqlState: '42S22', sqlMessage: "Unknown column 'bomb_time_remaining' in 'field list'"
> 
> [G5API-error-0.log](https://github.com/PhlexPlexico/G5API/files/11923105/G5API-error-0.log) [G5API-out-0.log](https://github.com/PhlexPlexico/G5API/files/11923106/G5API-out-0.log)

Yup looks like I forgot to include that column after testing, should be available shortly.

**Comment by Bunker56** [comment]
> Could you start a game, pause it, and use the game server console to take a look at that value?

of course

**Comment by Bunker56** [comment]
The problem is in the last letter... :)
"get5_remote_backup_url" = "http://g5test.bunker56.ru/api/v2/backup"
however, in the source code - `public/backups`

**Comment by Bunker56** [comment]
image `g5api:2.0.1.1`

![Screenshot_35](https://github.com/PhlexPlexico/G5API/assets/91856368/ca704ff9-17c0-431d-a3a8-ffb7d58e9377)

**Comment by PhlexPlexico** [comment]
Ah sorry, I forgot to add, can you also check the `get5_remote_backup_header_key` and `get5_remote_backup_header_value`? It seems your game server is replacing this value, I would check your `live.cfg`, `warmup.cfg` and `knife.cfg`, as well as your `server.cfg` to ensure this value is not getting unset.

**Comment by PhlexPlexico** [comment]
There, found out there was a get5 bug. Fixed the issue on my end with better practices in place, so now it should work as intended :)

**Comment by Bunker56** [comment]
I'm going to try it now... 20 minutes...

**Comment by Bunker56** [comment]
What`s about get5 0.15?

**Comment by PhlexPlexico** [comment]
It's an update to fix some issues with cvars being stored/not stored. You should just update to it just to be on latest

**Comment by Bunker56** [comment]
0.14.7 works, 0.15 for some reason did not start... Let me run in a new image first from 0.14, and later I'll start 0.15

**Comment by PhlexPlexico** [comment]
Oop thanks for the heads up, missed a check on a version. New version should be out soon!

**Comment by Bunker56** [comment]
already out...

**Comment by PhlexPlexico** [comment]
Nah, it appears to still be building :) 5 more minutes and it should be good!

**Comment by Bunker56** [comment]
Yeah. I see.

**Comment by Bunker56** [comment]
Perfectly!... Everything works, and with a minimum of plugin settings, I installed only the server id...

**Comment by Bunker56** [comment]
I have one more question - how is utility damage calculated, I can't find a clear explanation.

**Comment by PhlexPlexico** [comment]
Gett5 reports the utility damage at the end of each round. It's in the stats system, which I believe is any type of damage from utility - molotovs, grenades, etc.

http://splewis.github.io/get5/latest/stats_system/#example

**Comment by Bunker56** [comment]
Thanks. :)
