### ISSUE TITLE
[BUG] Typo `match_spectator` table name

### ISSUE THREAD

**Issue by thboss** [PhlexPlexico/G5API#255]
![image](https://github.com/PhlexPlexico/G5API/assets/40491968/514974c4-5ba3-4063-b663-997b4596c589)

https://github.com/PhlexPlexico/G5API/blob/717295069d20ab31b0a32a7489640ac05e7f067b/src/routes/matches/matches.js#L1233

**Comment by PhlexPlexico** [comment]
Should be fixed on the `next` branch now :) thanks for the report!
