### ISSUE TITLE
[BUG] Server RCON Issues

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#32]
**Describe the bug**
Two things are currently not working in Server calls. The first is a breaking bug, since there is no queue implemented in the RCON library I'm using, it means that we cannot make sequential calls in the application (yet). See [here](https://github.com/EnriqCG/rcon-srcds/pull/5).

Secondly, authenticating is only needed to be done once, so we don't really need it in each call, or else it is going to clog up the console/log with `Unable to authenticate to server. Error: Already Authenticated`. 

Both these issues will have to be adjusted in such a way that doesn't break the application. But right now creating matches is not sustainable and we must wait for fixes/make fixes ourselves.

**To Reproduce**
1. Create a match with any given server.

**Expected behavior**
Match should be created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Postman API

**Comment by PhlexPlexico** [comment]
First problem is solved, looking into rcon-srcds there is a flag "Authenticated" which we can easily check. Next is the queue issue which we shall await the PR to hopefully be merged!

**Comment by EnriqCG** [comment]
I'm working on merging https://github.com/EnriqCG/rcon-srcds/pull/5 ASAP after I'm done thoroughly testing the changes!

**Comment by PhlexPlexico** [comment]
Awesome! Thank you very much for your hard work @EnriqCG 😄

**Comment by EnriqCG** [comment]
`rcon-srcds` v1.2.0 has been released (yay!) to [npm](https://www.npmjs.com/package/rcon-srcds) and includes packet queuing which should solve your sequential call problems.

**Comment by PhlexPlexico** [comment]
Awesome! Thank you very much @EnriqCG!
