### ISSUE TITLE
[Request] API documentation with Swagger

### ISSUE THREAD

**Issue by ringvold** [PhlexPlexico/G5API#35]
**Is your feature request related to a problem? Please describe.**
I want to implement a client for the API and would like an easy accessible documentation for the endpoints and its responses.
Unfortunately the current jsdoc seems more aimed towards developers of the  G5API application and not consumers of the API.

**Describe the solution you'd like**
This can be done with Swagger as mentioned in another issue. There are several ways to realize this but I think the most prudent would be to have the swagger definitions close to the implementation as possible so it easier to keep it up to date.

The package [swagger-express](https://www.npmjs.com/package/swagger-express) can get the config from different places where jsdoc is one of them.
I'm not sure if swagger-express does this but swagger supports making request directly from swagger UI and can also show examples of the expected response for the endpoints.

Example of swagger ui for G5API:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/185551/84780178-8c091b00-afe5-11ea-8ca1-8f12b374d3c8.png">
Example of detailed information for an endpoint:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/185551/84780318-b8bd3280-afe5-11ea-8082-d73a38b280db.png">

See here for an full example of an API documented with swagger UI: https://petstore.swagger.io/

**Describe alternatives you've considered**
I'm trying out Haskell and a project called Servant that can generate code for clients in different languages as well as swagger documentation, but this is duplication of work and it is likely that this will diverge from the real implementation.

There are also a lot of other documentation projects that can be used but one of the big pros with swagger is that it can be generated and would not need that much manual upkeep.

**Additional context**
I might implement swagger-express to see how it works and create a PR.

**Comment by PhlexPlexico** [comment]
Goes hand in hand with #7 as well. I think I've combed through most of the docs to make sure that there wasn't duplicates at all. But this would be a good thing to use I believe. As long as its free, I don't see any issue with it, especially if it makes it easier for people to implement front-ends with it!

If you'd like to give a stab at it, I'll wait before poking around in it, if not let me know and I can probably start working on it in a few weeks here!

**Comment by PhlexPlexico** [comment]
Rotues:

- [ ] API
- [ ] Matches
- [ ] Matchserver
- [ ] Leaderboard
- [ ] Mapstats
- [ ] Playerstats
- [ ] Seasons
- [ ] Server
- [ ] Teams
- [ ] Users
- [ ] Vetoes

**Comment by PhlexPlexico** [comment]
Slowly but surely getting the hang of this. Just hope that the global statements are taking effect. The availability_fix branch will bring in and replace some more routes with Swagger.

**Comment by PhlexPlexico** [comment]
Every route has been moved to swagger. Now closing!
