### ISSUE TITLE
[STYLE] `int` as JSDoc Type

### ISSUE THREAD

**Issue by KokosnussDEV** [PhlexPlexico/G5API#38]
## What is wrong
In your code you are using `int` to describe a `number` in JSDoc. The type `int` does not exist as a seperate type to describe a type of number in JavaScript.

## Solution
Change `int` to `number` for a correct documentation

**Comment by PhlexPlexico** [comment]
Currently working on getting PR #36 integrated into the project, so this will be moving away from JSDoc, and more toward Swagger. I think I may just leave them as-is for now and continue attempting to get swagger fully functional, as well as updating endpoints to be more (as @ringvold stated) "RESTy".

**Comment by PhlexPlexico** [comment]
I do realize that there still may be some coverage with JSDoc still with some built-in functions that I have made, I think it may be okay to fix these as well.

**Comment by PhlexPlexico** [comment]
d7470e1 removes all `@param {int}` and has replaced it with `@param {number}` accordingly.
