### ISSUE TITLE
[Request] Step by Step installation procedure [OSX,Linux,WSL]

### ISSUE THREAD

**Issue by xe1os** [PhlexPlexico/G5API#48]
**Is your feature request related to a problem? Please describe.**
Request

**Describe the solution you'd like**
Detailed installation procedure

**Describe alternatives you've considered**
No

**Additional context**
Helpful for beginners.

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/G5API/wiki

Please see the wiki for detailed instructions :) installation and configuration are located there, as per issue #33! Let me know if there's anything holding you up from those instructions.

**Comment by xe1os** [comment]
@PhlexPlexico thank you for your response.

I'm trying to follow the steps mentioned in the wiki.

Getting below error when executed `yarn migrate-prod-create && yarn migrate-prod-upgrade` on production config

![yarn_db-migrate-error](https://user-images.githubusercontent.com/39219862/95753306-107f5800-0cbf-11eb-9e04-13a5861fdb46.jpg)

I've changed it to `yarn migrate-create-prod && yarn migrate-prod-upgrade`

Still getting below error.

![yarn_db-migrate-error2](https://user-images.githubusercontent.com/39219862/95753353-21c86480-0cbf-11eb-8a02-082ae9234bc5.jpg)

**Comment by PhlexPlexico** [comment]
Hi!

I'm assuming the issue was resolved since you closed it? Did you edit the proper config template over? In this case `production.json.template` to `production.json` in the same folder and filled out the values?

**Comment by xe1os** [comment]
@PhlexPlexico yup i made it work. It didn't work for me when i tried in OSX. It worked on WSL2 :) Thanks for the help!!

**Comment by PhlexPlexico** [comment]
Very odd it wasn't working in OSX! It's where I started development with this! What were you running into an issue if you don't mind, so I can adjust the wiki accordingly?

Thanks!

**Comment by xe1os** [comment]
@PhlexPlexico i missed installing the dependencies using `npm install`. Now made it work both in OSX and WSL2 :) Kudos to your work <3

**Comment by lukasz922** [comment]
Hi 
@PhlexPlexico  @xe1os You had something like this after calling the yarn start command
I have productions.json and  productions.json.template 
Productions.json  configured 


![obraz](https://user-images.githubusercontent.com/50584055/96048829-6dbe0980-0e77-11eb-825f-6176486e4c0e.png)

**Comment by PhlexPlexico** [comment]
It shouldn't be `productionS.json`. Notice the extra S you have at the end before the extension. It should just be `production.json` :)

**Comment by PhlexPlexico** [comment]
Also, as the red text states, you do not have `NODE_ENV` set as any of your environment variables. 

So if you're running linux, please set your environment variable:
`export NODE_ENV=production`

**Comment by lukasz922** [comment]
Thx @PhlexPlexico  its worked. i use yarn start  have problems in 
node_redis: Warning: Redis server does not require a password, but a password was supplied.
hmm

**Comment by lukasz922** [comment]
hmmm 

after doing export NODE_ENV=production  i have to 
![image](https://user-images.githubusercontent.com/50584055/96116886-7b13dc00-0ee9-11eb-9d2b-8ec8a3a0f76a.png)

**Comment by PhlexPlexico** [comment]
Well I'm sure there is not much difference between `yarn` and `npm`, but I have not tested with npm. So I can't say whether that's the problem or not. There's an array of issues since it's not project specific by the looks of it (it's using `nodemon` which just restarts the app if there's any changes to the files).

A few things after googling this error have brought me upon here:
https://stackoverflow.com/a/32444643/2124946
https://flummox-engineering.blogspot.com/2019/01/yarn-error-enomem-not-enough-memory-scandir-node.html

What version of node and npm are you using? That could also come into play.

**Comment by lukasz922** [comment]
![image](https://user-images.githubusercontent.com/50584055/96255594-774e8b00-0fb7-11eb-89fa-9b712a0b0146.png)

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/G5API/wiki/Ubuntu-Debian#install-nvm

Please make sure to follow the instructions for installation, NVM is a lot easier to manage node versions. You're about 5 versions behind for node which is most likely the problem

**Comment by lukasz922** [comment]
yeaa  Works, waiting for updates and I will test
