### ISSUE TITLE
[Request] Flags for servers

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#51]
**Is your feature request related to a problem? Please describe.**
Add in a new column for flags on a server. This way it can geographically show where any public servers may lie to get better connections.

**Describe the solution you'd like**
Two character code database field for flags under the game server table.

**Describe alternatives you've considered**

**Additional context**

**Comment by KokosnussDEV** [comment]
This is a great idea! 👍
