### ISSUE TITLE
[BUG] SQL Running out of connections

### ISSUE THREAD

**Issue by YungGhost1377** [PhlexPlexico/G5API#59]
Hello, this is log before crash. Help me please :)
https://pastebin.com/Xz18i7Ey

**Comment by YungGhost1377** [comment]
+
```
::ffff:127.0.0.1 - - [05/Dec/2020:07:33:07 +0000] "GET /servers/1 HTTP/1.1" 200 166 "http://rsp.yungghost.ovh/match/10" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
GET /matches/10/cancel 200 16.974 ms - 52
::ffff:127.0.0.1 - - [05/Dec/2020:07:33:16 +0000] "GET /matches/10/cancel HTTP/1.1" 200 52 "http://rsp.yungghost.ovh/match/10" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
Match is already finalized.
POST /match/10/finish/ 500 2.857 ms - 41
```

**Comment by PhlexPlexico** [comment]
When submitting a report please make sure to use the outlined ticket as it makes it way easier to debug. 

Can you reproduce this crash?
What were you doing when this crashed?
What's your collection pool number set to in your settings?

Thanks!

**Comment by YungGhost1377** [comment]
The crash basically happens on its own, even if the matches are not running, and it can also crash when, for example, I add a spectator or a player to a match.
http://rsp.yungghost.ovh
My spec:
Apache MPM-ITK, PHP module 7.2.24-0ubuntu0.18.04.7, PHP-FPM 7.2.24-0ubuntu0.18.04.7, awstats 7.6+dfsg-2, logrotate 3.11.0-0.1ubuntu1, nginx 1.16.1-1~bionic

MySQL 5.7.32-0ubuntu0.18.04.1

PHP 7.1 CGI

mariadb-10.3.27

Ubuntu 18

**Comment by YungGhost1377** [comment]
> When submitting a report please make sure to use the outlined ticket as it makes it way easier to debug. 
> 
> 
> 
> Can you reproduce this crash?
> 
> What were you doing when this crashed?
> 
> What's your collection pool number set to in your settings?
> 
> 
> 
> Thanks!

(What's your collection pool number set to in your settings?) -- What is it ? sry I don't understand (maybe production ?)

**Comment by PhlexPlexico** [comment]
Well first off, this API doesn't use PHP at all, so that shouldn't matter.

Inside the `config/production.json` or whatever environment you're using (the template you copied) has a connection pool limit. You may need to increase this to a higher number than 15. Try 50.

https://github.com/PhlexPlexico/G5API/blob/b5143392eb15f0ce15fdeaa2a2d991f8b0efb4af/config/production.json.template#L22

**Comment by PhlexPlexico** [comment]
#54 is the related issue. If you up that connection limit it should work fine.

**Comment by YungGhost1377** [comment]
> Well first off, this API doesn't use PHP at all, so that shouldn't matter.
> 
> 
> 
> Inside the `config/production.json` or whatever environment you're using (the template you copied) has a connection pool limit. You may need to increase this to a higher number than 15. Try 50.
> 
> 
> 
> https://github.com/PhlexPlexico/G5API/blob/b5143392eb15f0ce15fdeaa2a2d991f8b0efb4af/config/production.json.template#L22

How much do you use?

**Comment by PhlexPlexico** [comment]
I have zero clue as to what's on my instance at this point because of the amount of testing. At one time it was 200, which is an absurd amount, so I think 50 should be more than enough.


And fair, but next time if you have another but the Bug template will show you what needs to be provided :) 

Thank you!,

**Comment by YungGhost1377** [comment]
Ok, thx!

**Comment by YungGhost1377** [comment]
and it may be due to the fact that I use docker for mariandb?

**Comment by YungGhost1377** [comment]
I started using regular mysql instead of marian, and the problem seems to be solved

**Comment by PhlexPlexico** [comment]
Alright well that works too I suppose. If the issue arises again, feel free to re-open this issue.

Thanks!
