### ISSUE TITLE
[BUG] Doesn't authorize steam

### ISSUE THREAD

**Issue by furzich2015** [PhlexPlexico/G5API#66]
Installed g5api and g5v for a LAN test.
Raised g5API:
![image](https://user-images.githubusercontent.com/36245898/105086600-e699b680-5aa1-11eb-91c3-9277d63fc3c6.png)

Raised g5v:
![image](https://user-images.githubusercontent.com/36245898/105086688-0cbf5680-5aa2-11eb-8e83-e61ffb658f81.png)

The site has loaded:
![image](https://user-images.githubusercontent.com/36245898/105086891-560fa600-5aa2-11eb-8533-e832d2e2dd50.png)

I try to log in to Steam, and I get this error:
![image](https://user-images.githubusercontent.com/36245898/105086963-70498400-5aa2-11eb-8fe9-f2cd6ac7d97d.png)

ALL VERSION:
![image](https://user-images.githubusercontent.com/36245898/105087207-d3d3b180-5aa2-11eb-8cbf-9783956bc8cb.png)

СONFIG:
production.json
![image](https://user-images.githubusercontent.com/36245898/105087882-cff45f00-5aa3-11eb-9d74-397c9a6880e4.png)
vue.config.js
![image](https://user-images.githubusercontent.com/36245898/105087922-e13d6b80-5aa3-11eb-914a-a27ecc4de2fd.png)

LOG:
![image](https://user-images.githubusercontent.com/36245898/105087289-ee0d8f80-5aa2-11eb-9679-faedfb31c893.png)

What could be the problem?

**Comment by PhlexPlexico** [comment]
Inside your production.json file, the hostname must contain http:// :)

```json
{
  "server": {
    "port": 3301 ,
    "hostname": "http://192.168.1.20"
....
  }
}```

**Comment by furzich2015** [comment]
Its work, i dont see this ^^
Thanks <3
![image](https://user-images.githubusercontent.com/36245898/105105182-3dac8500-5abc-11eb-8304-c5eb42d2decf.png)
