### ISSUE TITLE
[Update] Fix documentation

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#7]
Copy paste code really sucks. Need to comb through all my function and make sure documentation still makes sense.

**Comment by ringvold** [comment]
Apropos documentation. Let me hijack this issue. :P 
Have you considered using something like [swagger](https://swagger.io/) to document the web API? I think it could make it easier to implement clients.

**Comment by PhlexPlexico** [comment]
Hmm, I haven't really looked into it. However, I am using JSDoc to document already, so if you run the command within the project you should get your (poorly) formatted documentation of the API. Buuuuuut that being said, I wouldn't mind making it neater and if using a different tool makes it easier, then that may be the case! I'll take a peek into it :)

**Comment by PhlexPlexico** [comment]
Closing as is now duplicate of #35
