### ISSUE TITLE
[Feature] Improve Database Tables

### ISSUE THREAD

**Issue by PhlexPlexico** [PhlexPlexico/G5API#73]
**Is your feature request related to a problem? Please describe.**
Right now there is a lot of cleanup that can be done on the database tables. For example, looking at the `player_stats` table. all the integer values can be set to `DEFAULT 0 NOT NULL` so we can report everything on the front end, instead of just providing blank values and having to get the front-end to do that work.

**Describe the solution you'd like**
Create a new `db-migrate` script to alter the tables to be a bit more strict.

**Describe alternatives you've considered**
Manually doing it, but it's better if it's in a script.

**Additional context**
The only concern would be inserts in the future and checking if they still work as intended, but the tests should catch these.

**Comment by 925916995** [comment]
Now can get5web support UTF-8?

**Comment by PhlexPlexico** [comment]
G5API supports utf-8 encoding out of the box :)
