### ISSUE TITLE
[Request] Discord Bot

### ISSUE THREAD

**Issue by thboss** [PhlexPlexico/G5API#77]
**Is your feature request related to a problem? Please describe.**
No.

**Describe alternatives you've considered**
Create a discord bot to setup matches.

**Additional context**
I'm planning to create a discord bot to setup matches (solo teams), does the API has the appropriate requirements to do that?

**Comment by KokosnussDEV** [comment]
Yes. You can use the api to create matches as well as teams etc. Just take a look at the API Docs and you'll be able to find out what endpoints to use.
(Please close @PhlexPlexico)

**Comment by PhlexPlexico** [comment]
Also please note there is a bot that does this for PUGs too :) you can probably reference systems from there and take a look at what API calls are made from it. Just remember you need the API key of your account to make these calls. It's just included in the call:

```json
{
  [
    "user_id": 1,
    "api_key": "your_api_key_here"
    "other_keys": "..."
  ]
}
```

And here's the bot I've made already: https://github.com/phlexplexico/G5-Bot

Link to API docs: https://phlex.avidgamers.me/api/api-docs/

Also I believe this was posted once in the discussion tabs either in this project or G5V, so if you have any questions about it you can post in the discussions of either or :)

Thanks!

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/G5API/discussions/76 for reference here is the discussion!
