### ISSUE TITLE
[BUG] Player Nicknames Not Sanitized in Match Config

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#86]
"Optional: Player Nickname" does not check for `"`
That causes whole /api/teams as well as the creator's /api/teams/myteams JSON throw errors.
@PhlexPlexico

**Comment by PhlexPlexico** [comment]
https://github.com/PhlexPlexico/G5API/blob/69e85cc8f1a6f70fba569de66ef4f8216379e47f/routes/matches/matches.js#L1115-L1119 

Here's where the fix should be and we can probably just do a `.replace` on the name, easy enough fix!

**Comment by KokosnussDEV** [comment]
Try `replaceAll` if your node version allows it

**Comment by PhlexPlexico** [comment]
It actually doesn't, so you just do a simple regex to filter it out. However, this incorporates more problems when creating teams as well, so this may take longer to fix :)

**Comment by lukasz922** [comment]
It has to do with creating new matches  i have problems 

![image](https://user-images.githubusercontent.com/50584055/112665045-ebd90000-8e5a-11eb-8b6b-b818f1b14330.png)

**Comment by PhlexPlexico** [comment]
Most likely, especially if your users have any characters that can break the JSON (such as a team name). If not, it's usually something to do with get5.

**Comment by PhlexPlexico** [comment]
There, should be fixed.

**Comment by PhlexPlexico** [comment]
Just tested creating a team with quotes and players with quotes and ran into no issues. So I believe this can be resolved.
