### ISSUE TITLE
[Feature] Improve Player Stats for pug/no pug values

### ISSUE THREAD

**Issue by thboss** [PhlexPlexico/G5API#89]
**Is your feature request related to a problem? Please describe.**
Right now there is only endpoints `/api/leaderboard/players/pug` and `/api/leaderboard/players` to get all players leaderboards, But sometimes we focus on a specific player, so all players don't make sense

**Describe the solution you'd like**
Add endpoints to get single-player leaderboard, something like `/api/leaderboard/players/pug/:steam_id` and `/api/leaderboard/players/:steam_id` 

**Describe alternatives you've considered**
Right now I'm using a filter to focus on a specific player

**Additional context**
That's all, Thanks!

**Comment by PhlexPlexico** [comment]
Are you sure you're just not looking for `player_stats`?

https://github.com/PhlexPlexico/G5API/blob/04c9824a70cde080ef15ec11e601f9175c322ced/routes/playerstats.js#L258-L272

**Comment by thboss** [comment]
Yes, but `playerstats/:steam_id` fetches rows for each match played, also it mixes pugs and normal matches
for example this player https://phlex.avidgamers.me/api/playerstats/76561197966054204
but his data in pugs leaderboard 
```json
{"steamId":"76561197966054204","name":"GoosieMelon","kills":11,"deaths":15,"assists":5,"k1":4,"k2":2,"k3":1,"k4":0,"k5":0,"v1":0,"v2":0,"v3":0,"v4":0,"v5":0,"trp":21,"fba":0,"total_damage":1508,"hsk":4,"hsp":"36.36","average_rating":"0.81","wins":1,"total_maps":1}
```

**Comment by PhlexPlexico** [comment]
So you would like to maybe have a different route that separates playerstats based on pugs and no pugs?

**Comment by thboss** [comment]
Yes, I just would like to get data as same as `api/leaderboard/players` and `api/leaderboard/players/pug` routes but for single player  instead of all players.

**Comment by PhlexPlexico** [comment]
I think it would make more sense to be in `playerstats` since a leaderboard compares to others, and if you're comparing yourself to no one it's not much of a leaderboard :) but yeah, I see what you mean and I can probably add in the same statistics to `playerstats` as well!

**Comment by PhlexPlexico** [comment]
https://phlex.avidgamers.me/api/playerstats/76561198181941426/pug how does this look?

**Comment by thboss** [comment]
That looks good but I think it still mixes pugs and no-pugs
you can see statists for this player https://phlex.avidgamers.me/api/playerstats/76561197973388641/pug
but it doesn't match with his statists in https://phlex.avidgamers.me/api/leaderboard/players/pug
```json
{"steamId":"76561197973388641","name":"SaahLadd","kills":20,"deaths":10,"assists":4,"k1":5,"k2":3,"k3":3,"k4":0,"k5":0,"v1":0,"v2":1,"v3":0,"v4":0,"v5":0,"trp":21,"fba":0,"total_damage":2246,"hsk":11,"hsp":"55.00","average_rating":"1.56","wins":1,"total_maps":1}
```

**Comment by PhlexPlexico** [comment]
Yeah I was just trying something basic here (much like the leaderboards query). I think there will have to be a join on the match to check if it was a pug or not. I can do that and update once that's complete. But the layout of the data is looking correct at least? If so, I'll push what I can once it's fixed here!

**Comment by PhlexPlexico** [comment]
There, should be in place now. However, another way of doing this would to be to grab `playerstats` of a specific user, and do processing on the front end as well, since it's just calculating some numbers, too :)

**Comment by thboss** [comment]
Everything good now! Yeah, I know that but it's good to do the calculating in the API to get always the same data in the frontend and bot ^^
