### ISSUE TITLE
[Request] Remove player from the match

### ISSUE THREAD

**Issue by thboss** [PhlexPlexico/G5API#93]
**Is your feature request related to a problem? Please describe.**
I would like to see an endpoint to remove a player from a match unlike the `adduser` endpoint, there is already get5 command `get5_removeplayer` that could be used for that.

https://github.com/splewis/get5/blob/master/scripting/get5.sp#L396-L397

**Comment by PhlexPlexico** [comment]
Didn't realize that was a thing! Can add this in :)

**Comment by PhlexPlexico** [comment]
Let me know if this works out for you!

**Comment by thboss** [comment]
Perfect! Thank you :)
