### ISSUE TITLE
[Feature Request] Coach select between players passing to get5

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#96]
I know for some time, that you can make a player on a server with get5 a coach quite easily. Got me wondering. How hard it would be to implement the same kind of toggle the team cap has to also toggle who the coach is?

**Comment by PhlexPlexico** [comment]
Just going to add the wontfix label for now, since the functionality outright doesn't exist in get5, but it definitely is something that I will want to implement in the future should the feature be implemented :)

**Comment by PhlexPlexico** [comment]
Just awaiting the PR for this in get5, so I'm going to remove the `wontfix` label and maybe start some work as soon as it gets merged.

**Comment by kubo6472** [comment]
Yay, it wad merged 😄

**Comment by PhlexPlexico** [comment]
Oh, I thought I had closed this! Yup, it's merged and should be working as necessary, if there's an issue with it feel free to open another issue :)
