### ISSUE TITLE
[Bug] Console Errors On Season Dates / BO2 Does Not Load Properly

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#98]
Selecting a range of season dates, even though the latter date is in the future causes the season to not show up. There does not seem a way to un-select the range to turn it back into a one-day selection. The only resolution is to re-create the whole season.

**Comment by kubo6472** [comment]
Hi, so we just had the chance to fully test it and the veto itself now works. But as of now, the BO2 sidepick (the other team picks side on the one team's map) does not work.

**Comment by PhlexPlexico** [comment]
That would actually be the front end. I just pushed a patch to G5V that should resolve that issue!

**Comment by kubo6472** [comment]
Aight, pulling now.

**Comment by PhlexPlexico** [comment]
Also dependencies were updated too, so any security issues should be resolved now, too! But yeah, I was using the word "default" for side type, instead of "standard", and I think that's what was causing issues, oops!

**Comment by kubo6472** [comment]
The behavior for "default" for knife rounds on this BO2 does not work as intended. We probably got to stick to never knife then.

**Comment by PhlexPlexico** [comment]
Can you post the match config  that's being sent?

**Comment by kubo6472** [comment]
```
get5_status
{
"matchid": "62",
"maps": {
"map0": "de_mirage",
"map2": "de_dust2",
"map1": "de_overpass"
},
"loaded_config_file": "get5_match_config_backup0.txt",
"map_number": 1,
"team2": {
"current_map_score": 0,
"connected_clients": 5,
"ready": false,
"name": "UNIZA chlebatreba",
"series_score": 0,
"side": "T"
},
"team1": {
"current_map_score": 0,
"connected_clients": 4,
"ready": false,
"name": "Esport UPJŠ",
"series_score": 1,
"side": "CT"
},
"commit": "cb4705a",
"gamestate": 3,
"gamestate_string": "warmup",
"plugin_version": "0.7.2-dev+521",
"paused": false
}
```
this?
link to the match 62: https://g5.hexus.eu/match/62

**Comment by PhlexPlexico** [comment]
Did you update and setup deploy the latest G5V change? I see your side type says "default" when it should now say "standard".

**Comment by kubo6472** [comment]
I see, 21 secs ago

**Comment by kubo6472** [comment]
sorry, nope, did the update today morning

**Comment by kubo6472** [comment]
pulled and updated, checked the source, yet somehow: https://wamis.ml/3eNQXyz
could that be the service worker or smth?

**Comment by kubo6472** [comment]
oh, now: https://wamis.ml/2RiDE10 it leaves the options unselected. that could be fixed in SeasonsTable.vue, right?

**Comment by kubo6472** [comment]
> 
> 
> oh, now: https://wamis.ml/2RiDE10 it leaves the options unselected. that could be fixed in SeasonsTable.vue, right?

I replaced it myself there 4 times. (every occurence except "export default") and will let you know if that fixed my problem

**Comment by kubo6472** [comment]
yep it did. imma do a pr real quick

**Comment by kubo6472** [comment]
as of newest api and g5v the bo2 matches do not end if tied.

**Comment by PhlexPlexico** [comment]
How so? Does it go to the next match? I feel if the matches aren't being ended I think that's get5 not properly ending the matches?

**Comment by kubo6472** [comment]
> How so? Does it go to the next match? I feel if the matches aren't being ended I think that's get5 not properly ending the matches?

Sorry, I am not quite clear. I mean the series does not end, when the BO2 ends as tied. So after two maps with one team winning each the G5V "match" so the series doesn't end.

**Comment by PhlexPlexico** [comment]
Can you get the log files from the API near the end of the match? I want to see if it called the series finalized call.

**Comment by kubo6472** [comment]
[_jplApi_logs.txt](https://github.com/PhlexPlexico/G5API/files/6412028/_jplApi_logs.txt)
It is a docker container and I have not tested this on the one, that isn't, but every other state works and series finalized was called definitely yesterday on a BO1 match that used this dockered API

**Comment by PhlexPlexico** [comment]
I mean that's fair if it works on a BO1, but I'm trying to check to see if get5 is even calling `EndSeries`, because from what you're reporting, it seems the API isn't receiving that call. Next time it happens try and get the log from there. From what I can see though. match 32 seemed to have finished just fine.

**Comment by kubo6472** [comment]
> 
> 
> I mean that's fair if it works on a BO1, but I'm trying to check to see if get5 is even calling `EndSeries`, because from what you're reporting, it seems the API isn't receiving that call. Next time it happens try and get the log from there. From what I can see though. match 32 seemed to have finished just fine.

I will try to set something up, since I went to database and set the series end time to the end of the second match timestamp and set isUsed to 0 for that server.

**Comment by PhlexPlexico** [comment]
Okay well from the logs you sent me the only thing I can see is just calling round updates for match 32. If there's any logs for ` "/:match_id/map/:map_number/finish` (i.e. `POST /match/32/map/1/finish` let me know, because there should be a call right after that `/match/32/finish` and the logs attached don't show that, either.

**Comment by kubo6472** [comment]
okay, will try this a few more times tomorrow and will try to filter the logs for that /map/1/finish and then /finish

**Comment by PhlexPlexico** [comment]
Perfect, also sidenote that if you're not using the master branch, please be sure to check the error log too! 
`yarn pm2 logs --err --lines 250` or something to get the error output, since all the fail statements now end up in the error log!

**Comment by PhlexPlexico** [comment]
Hey kubo!

Any updates for this, or does it seem to be working as intended now? :)

Thanks!

**Comment by kubo6472** [comment]
I still can't get the tied BO2 to log any /match/id/finish calls when it should end. Also this is prob. the service worker issue. On the dockerized G5V I can't get the "standard" map veto type at all. It's still "default".

**Comment by PhlexPlexico** [comment]
The service worker is because your browser is caching the application. Another reason why you can't get it built is that the docker container probably isn't rebuilding the app. You'll either have to go into your docker container and run the `yarn build` command by yourself and place all the files in the proper directory (I don't know which it is, I didn't make the Docker files), or just blow away the container and recreate it. 

And that is leading me to believe it's possible that this is a get5 issue. In order to replicate you can get your match config, place it locally and have it play out and see what it does. In the meantime, could you also provide your get5 debug output? I would like to see what some variables are.

Thanks!

**Comment by PhlexPlexico** [comment]
I also think you can do `get5_debug 16` and in the sourcemod logs directory there will be a `get5_debug.log` that could help see if it's making any calls when the match is finalized.

**Comment by kubo6472** [comment]
So, I did not managed, to get logging working, yet. But I have some interesting findings. I nuked it twice or thrice. Not putting back the containerized G5V to eliminate some variables. I am running the same G5V that works but with a different API instance (the containerized one) from a different domain. So I made sure the source code contained standard instead of default. But for some reason, on this containerized API it still goes to default. But on the same front end, just a different G5API (non containerized), the standard knife type works flawlessly.

**Comment by PhlexPlexico** [comment]
Are you by chance using private windows/clearing cache before testing?

**Comment by kubo6472** [comment]
> 
> 
> Are you by chance using private windows/clearing cache before testing?

My method of CTRL+F5 just wasn't enough. After using other browser's private mode, it did work. Thanks. I will continue trying to log the stuff of /match/id/finished for the BO2s

**Comment by PhlexPlexico** [comment]
Sounds good, and if you wouldn't mind getting those debug values from get5 as well, that would help I believe in some of these cases :) I mainly want to check if the variable (or something whatever it's called) g_MatchBo2 is set to true or not.

Thanks!

**Comment by kubo6472** [comment]
> 
> 
> I also think you can do `get5_debug 16` and in the sourcemod logs directory there will be a `get5_debug.log` that could help see if it's making any calls when the match is finalized.

I executed the command on a recently started bo2 on a server. So I'm waiting rn

**Comment by kubo6472** [comment]
[get5_debuginfo.txt](https://github.com/PhlexPlexico/G5API/files/6432896/get5_debuginfo.txt)

**Comment by PhlexPlexico** [comment]
From what I can see from both the log file, and the API file that this was not a BO2 match. Since it's not only bound to BO2, it's something that I can't solve here. I would recommend that you take the [match config](https://g6.hexus.eu/api/matches/19/config) and that log file you gave me, and post it in an issue in the get5 repo. From the looks of the call it's trying to do this, even though that menu should be null:
https://github.com/splewis/get5/blob/6c7809209083e6b6c53d8ce34c67e8249645566c/scripting/get5.sp#L818-L820

Since this is something directly related to Get5, and not the API, or the front end, I can't do anything to resolve this issue. Sorry!

**Comment by kubo6472** [comment]
Sorry, I must've messed up the files. This was from two weeks ago. When you have 10 servers right next to each other, you get lost in that pretty easily. I checked back that match. Yep. That was a sequence of two BO1s cuz the veto did not work back then. I am trying to find what logs did I make yesterday then.

**Comment by kubo6472** [comment]
https://g6.hexus.eu/match/56
just played out this one to be tied 1:1 I haven't restarted the server, yet. But the get5_debug log is not there. I think it is created on reboot or something. I checked the get5_debug is set to 16 before and after the match played out.

**Comment by PhlexPlexico** [comment]
What you can do is run `get5_debuginfo ` and get the data from there as well. https://github.com/splewis/get5/wiki/Debugging-help

**Comment by kubo6472** [comment]
`Time: 05/09/2021 - 16:41:33
Plugin version: 0.7.2-dev+521
sourcemod_version = 1.10.0.6501
metamod_version = 1.11.0-dev+1143V
get5 git commit: cb4705a



Global state:
g_GameState = 0 (none)
g_MatchID = 
g_MapsToWin = 1
g_BO2Match = 0
g_LastVetoTeam = 0
g_MapPoolList (length 0) = 
g_MapsToPlay (length 0) = 
g_MapsLeftInVetoPool (length 0) = 
g_MatchTitle = 
g_PlayersPerTeam = 5
g_MinPlayersToReady = 1
g_MinSpectatorsToReady = 0
g_SkipVeto = 0
g_MatchSideType = 0
g_InScrimMode = 0
g_HasKnifeRoundStarted = 0
g_MapChangePending = 0
g_PendingSideSwap = 0
g_WaitingForRoundBackup = 0
g_SavedValveBackup = 0
g_DoingBackupRestoreNow = 0
g_ReadyTimeWaitingUsed = 0
Team info for team team1 (0):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = CT (3)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 3
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
Team info for team team2 (1):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = T (2)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 2
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
Team info for team spec (2):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0
Team info for team none (3):
g_TeamNames = 
g_TeamAuths (length 0) = 
g_TeamTags = 
g_FormattedTeamNames = 
g_TeamFlags = 
g_TeamLogos = 
g_TeamMatchTexts = 
g_TeamSide = none (0)
g_TeamSeriesScores = 0
g_TeamReadyOverride = 0
g_TeamStartingSide = 0
g_TeamPauseTimeUsed = 0
g_TeamPausesUsed = 0



Interesting cvars:
get5_allow_technical_pause = 1
get5_autoload_config = 
get5_check_auths = 1
get5_fixed_pause_time = 0
get5_kick_when_no_match_loaded = 1
get5_live_cfg = get5/live.cfg
get5_max_pause_time = 300
get5_max_pauses = 5
get5_mysql_force_matchid = NULL CVAR
get5_pausing_enabled = 1
get5_reset_pauses_each_half = 0
get5_web_api_url = 
mp_freezetime = 15
mp_halftime = 1
mp_halftime_duration = 15.0
mp_halftime_pausetimer = 0
mp_match_end_restart = 0
mp_maxrounds = 30
mp_overtime_enable = 0
mp_overtime_halftime_pausetimer = 0
mp_overtime_maxrounds = 6
mp_round_restart_delay = 7.0
mp_timelimit = 0
mp_warmup_pausetimer = 0
mp_warmuptime_all_players_connected = 60
sv_coaching_enabled = 0
tv_delay = 90
tv_enable = 1



Last log info from addons/sourcemod/logs/errors_20210506.log:
L 05/06/2021 - 15:30:51: Error log file session closed.
 L 05/06/2021 - 15:28:44: [get5_apistats.smx] Failed to create logo directory: resource/flash/econ/tournaments/teams
 L 05/06/2021 - 15:24:32: [get5_apistats.smx] Failed to create logo directory: resource/flash/econ/tournaments/teams
 L 05/06/2021 - 15:24:32: Info (map "de_dust2") (file "/hlserver/27917/csgo/addons/sourcemod/logs/errors_20210506.log")
 L 05/06/2021 - 15:24:32: SourceMod error session started
 


Last log info from addons/sourcemod/logs/get5_debug.log:
L 05/07/2021 - 04:27:16: [get5] Calling Get5_OnEvent(event name = player_disconnect)
 }
     "event": "player_disconnect"
     },
         "map_name": "de_vertigo"
         "map_number": 2,
         "client": "none",
     "params": {
     "matchid": "56",
 L 05/07/2021 - 04:27:16: [get5] get5_event: {
 


sm plugins list:
playercommands.smx: Player Commands by AlliedModders LLC: Misc. Player Commands (1.10.0.6501, http://www.sourcemod.net/)
antiflood.smx: Anti-Flood by AlliedModders LLC: Protects against chat flooding (1.10.0.6501, http://www.sourcemod.net/)
adminmenu.smx: Admin Menu by AlliedModders LLC: Administration Menu (1.10.0.6501, http://www.sourcemod.net/)
basecommands.smx: Basic Commands by AlliedModders LLC: Basic Admin Commands (1.10.0.6501, http://www.sourcemod.net/)
basevotes.smx: Basic Votes by AlliedModders LLC: Basic Vote Commands (1.10.0.6501, http://www.sourcemod.net/)
clientprefs.smx: Client Preferences by AlliedModders LLC: Client peferences and settings menu (1.10.0.6501, http://www.sourcemod.net/)
basecomm.smx: Basic Comm Control by AlliedModders LLC: Provides methods of controlling communication. (1.10.0.6501, http://www.sourcemod.net/)
nextmap.smx: Nextmap by AlliedModders LLC: Provides nextmap and sm_nextmap (1.10.0.6501, http://www.sourcemod.net/)
basebans.smx: Basic Ban Commands by AlliedModders LLC: Basic Banning Commands (1.10.0.6501, http://www.sourcemod.net/)
funcommands.smx: Fun Commands by AlliedModders LLC: Fun Commands (1.10.0.6501, http://www.sourcemod.net/)
reservedslots.smx: Reserved Slots by AlliedModders LLC: Provides basic reserved slots (1.10.0.6501, http://www.sourcemod.net/)
basechat.smx: Basic Chat by AlliedModders LLC: Basic Communication Commands (1.10.0.6501, http://www.sourcemod.net/)
admin-flatfile.smx: Admin File Reader by AlliedModders LLC: Reads admin files (1.10.0.6501, http://www.sourcemod.net/)
adminhelp.smx: Admin Help by AlliedModders LLC: Display command information (1.10.0.6501, http://www.sourcemod.net/)
get5.smx: Get5 by splewis:  (0.7.2-dev+521, https://github.com/splewis/get5)
sounds.smx: Sound Commands by AlliedModders LLC: Sound Commands (1.10.0.6501, http://www.sourcemod.net/)
franug_noagentsmodels.smx: SM Franug No Agents Models by Franc1sco franug:  (2.0, http://steamcommunity.com/id/franug)
get5_apistats.smx: Get5 API Integration - RIPEXT by splewis/phlexplexico: Records match stats to G5API. (2.0.2, https://github.com/phlexplexico/get5-web)
funvotes.smx: Fun Votes by AlliedModders LLC: Fun Vote Commands (1.10.0.6501, http://www.sourcemod.net/)
basetriggers.smx: Basic Info Triggers by AlliedModders LLC: Adds ff, timeleft, thetime, and others. (1.10.0.6501, http://www.sourcemod.net/)
`

get5_debuginfo from the tied match including the only errors displayed.

**Comment by PhlexPlexico** [comment]
And do you have the match config? From what I can see `mapsToWin` is only 1, which you sent 2, `matchID` is blank, which means the debug info didn't seem to get that, and `Bo2` flag is 0 which means it didn't get set. If you provide the match config as well you should be able to try loading the match through the console rather than through the web and can check those values of interest. But from what I can see, and if the match config provided doesn't have any issues that I can see, this is more of a get5 issue. However this has to be recreated through get5 itself by using the config and loading it locally on the server, and having to watch for the event call `OnSeriesResult`.

`Last log info from addons/sourcemod/logs/get5_debug.log:`

Can you get more information from that log file rather than just the player disconnect? There should be a map finish call, as well as a series finish call.

**Comment by PhlexPlexico** [comment]
Also I was looking in the get5 wiki for some more debugging hints, apparently it's `get5_debug 32` to store to the log that's located in the `sourcemod/logs` directory Would you be able to try and run a game with it and see if the `OnSeriesResult` is called at all when a BO2 ties?

My guess is that `g_BO2Match` isn't getting set in the match config setup for whatever reason, so this part of the logic doesn't fire and it just hits the default case and just sets the state to `Postgame`

https://github.com/splewis/get5/blob/6c7809209083e6b6c53d8ce34c67e8249645566c/scripting/get5.sp#L1014-L1017

I don't really have a server to test this anymore, so I'm not really able to get definitive proof myself, unfortunately

**Comment by kubo6472** [comment]
Had an opportunity to test it, works. Thx and sry it took so long.

**Comment by PhlexPlexico** [comment]
Hey no worries at all! Glad to hear it's resolved :)
