### ISSUE TITLE
[BUG] CVARS in season not sanitized

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#99]
**Describe the bug**
when you put "" in cvar in a season, it breaks

**To Reproduce**
1. create/edit a seaon
2. put "" in a cvar

**Expected behavior**
sanitized and passed onto the server in a string

**Comment by PhlexPlexico** [comment]
Commit https://github.com/PhlexPlexico/G5API/commit/b6aa4799ed1e6df7e83f90dd4992798b8470c982

Now sanitizes any strings that are being POSTed or PUT and will strip the quotes into escaped quotes.
`"": ` will now be `\"\": ` in the database.
`"": ""` will now be `\"\": \"\"` in the DB and output as `"": "\"\""`.
`"": "test"` will now be output as `"": "\"test\""`

Hope that covers all the cases?

**Comment by kubo6472** [comment]
I've nocited this completely randomly, so yea, I hope this covers all that I could've thought of.
